/*
Automatically generated by HaskellDirect (ihc.exe), version 0.21
Created: 22:02 ope, Tuesday 07 August, 2012
Command line: -o agentsvr3.hs --gen-headers -fno-export-list -d -dshow-passes --verbose agentsvr.IDL -fgen-variant-instances -fno-qualified-names -fno-export-list -fcom -fcoalesce-methods -fno-gen-binary-interface -fprefix-interface-name -fmaybe-optional-params
*/


#ifndef __INT64_DEFINED__
#ifdef __GNUC__
typedef long long int64;
typedef unsigned long long uint64;
#else
#ifdef _MSC_VER
typedef __int64 int64;
typedef unsigned __int64 uint64;
#else
/* Need some help here, please. */
#endif
#endif
#define __INT64_DEFINED__
#endif


#ifndef __AGENTSVR3_H__
#define __AGENTSVR3_H__
#ifndef __IAgent_FWD_DEFINED__
#define __IAgent_FWD_DEFINED__
typedef struct IAgent IAgent;
#endif
#ifndef __IAgentUserInput_FWD_DEFINED__
#define __IAgentUserInput_FWD_DEFINED__
typedef struct IAgentUserInput IAgentUserInput;
#endif
#ifndef __IAgentCommand_FWD_DEFINED__
#define __IAgentCommand_FWD_DEFINED__
typedef struct IAgentCommand IAgentCommand;
#endif
#ifndef __IAgentCommandEx_FWD_DEFINED__
#define __IAgentCommandEx_FWD_DEFINED__
typedef struct IAgentCommandEx IAgentCommandEx;
#endif
#ifndef __IAgentCommands_FWD_DEFINED__
#define __IAgentCommands_FWD_DEFINED__
typedef struct IAgentCommands IAgentCommands;
#endif
#ifndef __IAgentCommandsEx_FWD_DEFINED__
#define __IAgentCommandsEx_FWD_DEFINED__
typedef struct IAgentCommandsEx IAgentCommandsEx;
#endif
#ifndef __IAgentSpeechInputProperties_FWD_DEFINED__
#define __IAgentSpeechInputProperties_FWD_DEFINED__
typedef struct IAgentSpeechInputProperties IAgentSpeechInputProperties;
#endif
#ifndef __IAgentAudioOutputProperties_FWD_DEFINED__
#define __IAgentAudioOutputProperties_FWD_DEFINED__
typedef struct IAgentAudioOutputProperties IAgentAudioOutputProperties;
#endif
#ifndef __IAgentAudioOutputPropertiesEx_FWD_DEFINED__
#define __IAgentAudioOutputPropertiesEx_FWD_DEFINED__
typedef struct IAgentAudioOutputPropertiesEx IAgentAudioOutputPropertiesEx;
#endif
#ifndef __IAgentPropertySheet_FWD_DEFINED__
#define __IAgentPropertySheet_FWD_DEFINED__
typedef struct IAgentPropertySheet IAgentPropertySheet;
#endif
#ifndef __IAgentBalloon_FWD_DEFINED__
#define __IAgentBalloon_FWD_DEFINED__
typedef struct IAgentBalloon IAgentBalloon;
#endif
#ifndef __IAgentBalloonEx_FWD_DEFINED__
#define __IAgentBalloonEx_FWD_DEFINED__
typedef struct IAgentBalloonEx IAgentBalloonEx;
#endif
#ifndef __IAgentCharacter_FWD_DEFINED__
#define __IAgentCharacter_FWD_DEFINED__
typedef struct IAgentCharacter IAgentCharacter;
#endif
#ifndef __IAgentCharacterEx_FWD_DEFINED__
#define __IAgentCharacterEx_FWD_DEFINED__
typedef struct IAgentCharacterEx IAgentCharacterEx;
#endif
#ifndef __IAgentEx_FWD_DEFINED__
#define __IAgentEx_FWD_DEFINED__
typedef struct IAgentEx IAgentEx;
#endif
#ifndef __IAgentNotifySink_FWD_DEFINED__
#define __IAgentNotifySink_FWD_DEFINED__
typedef struct IAgentNotifySink IAgentNotifySink;
#endif
#ifndef __IAgentNotifySinkEx_FWD_DEFINED__
#define __IAgentNotifySinkEx_FWD_DEFINED__
typedef struct IAgentNotifySinkEx IAgentNotifySinkEx;
#endif
#ifndef __IAgentCommandWindow_FWD_DEFINED__
#define __IAgentCommandWindow_FWD_DEFINED__
typedef struct IAgentCommandWindow IAgentCommandWindow;
#endif
/*library AgentServerObjects*/
/*{*/
typedef struct IAgent IAgent;
typedef struct IAgentUserInput IAgentUserInput;
typedef struct IAgentCommand IAgentCommand;
typedef struct IAgentCommandEx IAgentCommandEx;
typedef struct IAgentCommands IAgentCommands;
typedef struct IAgentCommandsEx IAgentCommandsEx;
typedef struct IAgentSpeechInputProperties IAgentSpeechInputProperties;
typedef struct IAgentAudioOutputProperties IAgentAudioOutputProperties;
typedef struct IAgentAudioOutputPropertiesEx IAgentAudioOutputPropertiesEx;
typedef struct IAgentPropertySheet IAgentPropertySheet;
typedef struct IAgentBalloon IAgentBalloon;
typedef struct IAgentBalloonEx IAgentBalloonEx;
typedef struct IAgentCharacter IAgentCharacter;
typedef struct IAgentCharacterEx IAgentCharacterEx;
typedef struct IAgentEx IAgentEx;
typedef struct IAgentNotifySink IAgentNotifySink;
typedef struct IAgentNotifySinkEx IAgentNotifySinkEx;
typedef struct IAgentCommandWindow IAgentCommandWindow;
/*coclass AgentServer {};*/
typedef struct IAgentVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * Load) ( IAgent* This
                              , /*[in]*/VARIANT vLoadKey
                              , /*[ref, out]*/long* pdwCharID
                              , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * Unload) ( IAgent* This
                                , /*[in]*/long dwCharID );
   HRESULT (__stdcall * Register) ( IAgent* This
                                  , /*[in]*/IUnknown* punkNotifySink
                                  , /*[ref, out]*/long* pdwSinkID );
   HRESULT (__stdcall * Unregister) ( IAgent* This
                                    , /*[in]*/long dwSinkID );
   HRESULT (__stdcall * GetCharacter) ( IAgent* This
                                      , /*[in]*/long dwCharID
                                      , /*[ref, out]*/IDispatch** ppunkCharacter );
   HRESULT (__stdcall * GetSuspended) ( IAgent* This
                                      , /*[ref, out]*/long* pbSuspended );
} IAgentVtbl;

struct IAgent {
  struct IAgentVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgent_Load(This,vLoadKey,pdwCharID,pdwReqID) \
     (This)->lpVtbl->Load(This,vLoadKey,pdwCharID,pdwReqID)
#define IAgent_Unload(This,dwCharID) \
     (This)->lpVtbl->Unload(This,dwCharID)
#define IAgent_Register(This,punkNotifySink,pdwSinkID) \
     (This)->lpVtbl->Register(This,punkNotifySink,pdwSinkID)
#define IAgent_Unregister(This,dwSinkID) \
     (This)->lpVtbl->Unregister(This,dwSinkID)
#define IAgent_GetCharacter(This,dwCharID,ppunkCharacter) \
     (This)->lpVtbl->GetCharacter(This,dwCharID,ppunkCharacter)
#define IAgent_GetSuspended(This,pbSuspended) \
     (This)->lpVtbl->GetSuspended(This,pbSuspended)
#endif /*COBJMACROS*/
typedef struct IAgentUserInputVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetCount) ( IAgentUserInput* This
                                  , /*[ref, out]*/long* pdwCount );
   HRESULT (__stdcall * GetItemID) ( IAgentUserInput* This
                                   , /*[in]*/long dwItemIndex
                                   , /*[ref, out]*/long* pdwCommandID );
   HRESULT (__stdcall * GetItemConfidence) ( IAgentUserInput* This
                                           , /*[in]*/long dwItemIndex
                                           , /*[ref, out]*/long* plConfidence );
   HRESULT (__stdcall * GetItemText) ( IAgentUserInput* This
                                     , /*[in]*/long dwItemIndex
                                     , /*[ref, out]*/BSTR* pbszText );
   HRESULT (__stdcall * GetAllItemData) ( IAgentUserInput* This
                                        , /*[ref, out]*/VARIANT* pdwItemIndices
                                        , /*[ref, out]*/VARIANT* plConfidences
                                        , /*[ref, out]*/VARIANT* pbszText );
} IAgentUserInputVtbl;

struct IAgentUserInput {
  struct IAgentUserInputVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentUserInput_GetCount(This,pdwCount) \
     (This)->lpVtbl->GetCount(This,pdwCount)
#define IAgentUserInput_GetItemID(This,dwItemIndex,pdwCommandID) \
     (This)->lpVtbl->GetItemID(This,dwItemIndex,pdwCommandID)
#define IAgentUserInput_GetItemConfidence(This,dwItemIndex,plConfidence) \
     (This)->lpVtbl->GetItemConfidence(This,dwItemIndex,plConfidence)
#define IAgentUserInput_GetItemText(This,dwItemIndex,pbszText) \
     (This)->lpVtbl->GetItemText(This,dwItemIndex,pbszText)
#define IAgentUserInput_GetAllItemData(This,pdwItemIndices,plConfidences,pbszText) \
     (This)->lpVtbl->GetAllItemData(This,pdwItemIndices,plConfidences,pbszText)
#endif /*COBJMACROS*/
typedef struct IAgentCommandVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * SetCaption) ( IAgentCommand* This
                                    , /*[in]*/BSTR bszCaption );
   HRESULT (__stdcall * GetCaption) ( IAgentCommand* This
                                    , /*[ref, out]*/BSTR* pbszCaption );
   HRESULT (__stdcall * SetVoice) ( IAgentCommand* This
                                  , /*[in]*/BSTR bszVoice );
   HRESULT (__stdcall * GetVoice) ( IAgentCommand* This
                                  , /*[ref, out]*/BSTR* pbszVoice );
   HRESULT (__stdcall * SetEnabled) ( IAgentCommand* This
                                    , /*[in]*/long bEnabled );
   HRESULT (__stdcall * GetEnabled) ( IAgentCommand* This
                                    , /*[ref, out]*/long* pbEnabled );
   HRESULT (__stdcall * SetVisible) ( IAgentCommand* This
                                    , /*[in]*/long bVisible );
   HRESULT (__stdcall * GetVisible) ( IAgentCommand* This
                                    , /*[ref, out]*/long* pbVisible );
   HRESULT (__stdcall * SetConfidenceThreshold) ( IAgentCommand* This
                                                , /*[in]*/long lThreshold );
   HRESULT (__stdcall * GetConfidenceThreshold) ( IAgentCommand* This
                                                , /*[ref, out]*/long* plThreshold );
   HRESULT (__stdcall * SetConfidenceText) ( IAgentCommand* This
                                           , /*[in]*/BSTR bszTipText );
   HRESULT (__stdcall * GetConfidenceText) ( IAgentCommand* This
                                           , /*[ref, out]*/BSTR* pbszTipText );
   HRESULT (__stdcall * GetID) ( IAgentCommand* This
                               , /*[ref, out]*/long* pdwID );
} IAgentCommandVtbl;

struct IAgentCommand {
  struct IAgentCommandVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentCommand_SetCaption(This,bszCaption) \
     (This)->lpVtbl->SetCaption(This,bszCaption)
#define IAgentCommand_GetCaption(This,pbszCaption) \
     (This)->lpVtbl->GetCaption(This,pbszCaption)
#define IAgentCommand_SetVoice(This,bszVoice) \
     (This)->lpVtbl->SetVoice(This,bszVoice)
#define IAgentCommand_GetVoice(This,pbszVoice) \
     (This)->lpVtbl->GetVoice(This,pbszVoice)
#define IAgentCommand_SetEnabled(This,bEnabled) \
     (This)->lpVtbl->SetEnabled(This,bEnabled)
#define IAgentCommand_GetEnabled(This,pbEnabled) \
     (This)->lpVtbl->GetEnabled(This,pbEnabled)
#define IAgentCommand_SetVisible(This,bVisible) \
     (This)->lpVtbl->SetVisible(This,bVisible)
#define IAgentCommand_GetVisible(This,pbVisible) \
     (This)->lpVtbl->GetVisible(This,pbVisible)
#define IAgentCommand_SetConfidenceThreshold(This,lThreshold) \
     (This)->lpVtbl->SetConfidenceThreshold(This,lThreshold)
#define IAgentCommand_GetConfidenceThreshold(This,plThreshold) \
     (This)->lpVtbl->GetConfidenceThreshold(This,plThreshold)
#define IAgentCommand_SetConfidenceText(This,bszTipText) \
     (This)->lpVtbl->SetConfidenceText(This,bszTipText)
#define IAgentCommand_GetConfidenceText(This,pbszTipText) \
     (This)->lpVtbl->GetConfidenceText(This,pbszTipText)
#define IAgentCommand_GetID(This,pdwID) \
     (This)->lpVtbl->GetID(This,pdwID)
#endif /*COBJMACROS*/
typedef struct IAgentCommandExVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * SetHelpContextID) ( IAgentCommandEx* This
                                          , /*[in]*/long ulID );
   HRESULT (__stdcall * GetHelpContextID) ( IAgentCommandEx* This
                                          , /*[ref, out]*/long* pulID );
   HRESULT (__stdcall * SetVoiceCaption) ( IAgentCommandEx* This
                                         , /*[in]*/BSTR bszVoiceCaption );
   HRESULT (__stdcall * GetVoiceCaption) ( IAgentCommandEx* This
                                         , /*[ref, out]*/BSTR* pbszVoiceCaption );
} IAgentCommandExVtbl;

struct IAgentCommandEx {
  struct IAgentCommandExVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentCommandEx_SetHelpContextID(This,ulID) \
     (This)->lpVtbl->SetHelpContextID(This,ulID)
#define IAgentCommandEx_GetHelpContextID(This,pulID) \
     (This)->lpVtbl->GetHelpContextID(This,pulID)
#define IAgentCommandEx_SetVoiceCaption(This,bszVoiceCaption) \
     (This)->lpVtbl->SetVoiceCaption(This,bszVoiceCaption)
#define IAgentCommandEx_GetVoiceCaption(This,pbszVoiceCaption) \
     (This)->lpVtbl->GetVoiceCaption(This,pbszVoiceCaption)
#endif /*COBJMACROS*/
typedef struct IAgentCommandsVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetCommand) ( IAgentCommands* This
                                    , /*[in]*/long dwCommandID
                                    , /*[ref, out]*/IUnknown** ppunkCommand );
   HRESULT (__stdcall * GetCount) ( IAgentCommands* This
                                  , /*[ref, out]*/long* pdwCount );
   HRESULT (__stdcall * SetCaption) ( IAgentCommands* This
                                    , /*[in]*/BSTR bszCaption );
   HRESULT (__stdcall * GetCaption) ( IAgentCommands* This
                                    , /*[ref, out]*/BSTR* pbszCaption );
   HRESULT (__stdcall * SetVoice) ( IAgentCommands* This
                                  , /*[in]*/BSTR bszVoice );
   HRESULT (__stdcall * GetVoice) ( IAgentCommands* This
                                  , /*[ref, out]*/BSTR* pbszVoice );
   HRESULT (__stdcall * SetVisible) ( IAgentCommands* This
                                    , /*[in]*/long bVisible );
   HRESULT (__stdcall * GetVisible) ( IAgentCommands* This
                                    , /*[ref, out]*/long* pbVisible );
   HRESULT (__stdcall * Add) ( IAgentCommands* This
                             , /*[in]*/BSTR bszCaption
                             , /*[in]*/BSTR bszVoice
                             , /*[in]*/long bEnabled
                             , /*[in]*/long bVisible
                             , /*[ref, out]*/long* pdwID );
   HRESULT (__stdcall * Insert) ( IAgentCommands* This
                                , /*[in]*/BSTR bszCaption
                                , /*[in]*/BSTR bszVoice
                                , /*[in]*/long bEnabled
                                , /*[in]*/long bVisible
                                , /*[in]*/long dwRefID
                                , /*[in]*/long bBefore
                                , /*[ref, out]*/long* pdwID );
   HRESULT (__stdcall * Remove) ( IAgentCommands* This
                                , /*[in]*/long dwID );
   HRESULT (__stdcall * RemoveAll) ( IAgentCommands* This );
} IAgentCommandsVtbl;

struct IAgentCommands {
  struct IAgentCommandsVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentCommands_GetCommand(This,dwCommandID,ppunkCommand) \
     (This)->lpVtbl->GetCommand(This,dwCommandID,ppunkCommand)
#define IAgentCommands_GetCount(This,pdwCount) \
     (This)->lpVtbl->GetCount(This,pdwCount)
#define IAgentCommands_SetCaption(This,bszCaption) \
     (This)->lpVtbl->SetCaption(This,bszCaption)
#define IAgentCommands_GetCaption(This,pbszCaption) \
     (This)->lpVtbl->GetCaption(This,pbszCaption)
#define IAgentCommands_SetVoice(This,bszVoice) \
     (This)->lpVtbl->SetVoice(This,bszVoice)
#define IAgentCommands_GetVoice(This,pbszVoice) \
     (This)->lpVtbl->GetVoice(This,pbszVoice)
#define IAgentCommands_SetVisible(This,bVisible) \
     (This)->lpVtbl->SetVisible(This,bVisible)
#define IAgentCommands_GetVisible(This,pbVisible) \
     (This)->lpVtbl->GetVisible(This,pbVisible)
#define IAgentCommands_Add(This,bszCaption,bszVoice,bEnabled,bVisible,pdwID) \
     (This)->lpVtbl->Add(This,bszCaption,bszVoice,bEnabled,bVisible,pdwID)
#define IAgentCommands_Insert(This,bszCaption,bszVoice,bEnabled,bVisible,dwRefID,bBefore,pdwID) \
     (This)->lpVtbl->Insert(This,bszCaption,bszVoice,bEnabled,bVisible,dwRefID,bBefore,pdwID)
#define IAgentCommands_Remove(This,dwID) \
     (This)->lpVtbl->Remove(This,dwID)
#define IAgentCommands_RemoveAll(This) \
     (This)->lpVtbl->RemoveAll(This)
#endif /*COBJMACROS*/
typedef struct IAgentCommandsExVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetCommandEx) ( IAgentCommandsEx* This
                                      , /*[in]*/long dwCommandID
                                      , /*[ref, out]*/IAgentCommandEx** ppCommandEx );
   HRESULT (__stdcall * SetDefaultID) ( IAgentCommandsEx* This
                                      , /*[in]*/long dwID );
   HRESULT (__stdcall * GetDefaultID) ( IAgentCommandsEx* This
                                      , /*[ref, out]*/long* pdwID );
   HRESULT (__stdcall * SetHelpContextID) ( IAgentCommandsEx* This
                                          , /*[in]*/long ulHelpID );
   HRESULT (__stdcall * GetHelpContextID) ( IAgentCommandsEx* This
                                          , /*[ref, out]*/long* pulHelpID );
   HRESULT (__stdcall * SetFontName) ( IAgentCommandsEx* This
                                     , /*[in]*/BSTR bszFontName );
   HRESULT (__stdcall * GetFontName) ( IAgentCommandsEx* This
                                     , /*[ref, out]*/BSTR* pbszFontName );
   HRESULT (__stdcall * SetFontSize) ( IAgentCommandsEx* This
                                     , /*[in]*/long lFontSize );
   HRESULT (__stdcall * GetFontSize) ( IAgentCommandsEx* This
                                     , /*[ref, out]*/long* lFontSize );
   HRESULT (__stdcall * SetVoiceCaption) ( IAgentCommandsEx* This
                                         , /*[in]*/BSTR bszVoiceCaption );
   HRESULT (__stdcall * GetVoiceCaption) ( IAgentCommandsEx* This
                                         , /*[ref, out]*/BSTR* bszVoiceCaption );
   HRESULT (__stdcall * AddEx) ( IAgentCommandsEx* This
                               , /*[in]*/BSTR bszCaption
                               , /*[in]*/BSTR bszVoice
                               , /*[in]*/BSTR bszVoiceCaption
                               , /*[in]*/long bEnabled
                               , /*[in]*/long bVisible
                               , /*[in]*/long ulHelpID
                               , /*[ref, out]*/long* pdwID );
   HRESULT (__stdcall * InsertEx) ( IAgentCommandsEx* This
                                  , /*[in]*/BSTR bszCaption
                                  , /*[in]*/BSTR bszVoice
                                  , /*[in]*/BSTR bszVoiceCaption
                                  , /*[in]*/long bEnabled
                                  , /*[in]*/long bVisible
                                  , /*[in]*/long ulHelpID
                                  , /*[in]*/long dwRefID
                                  , /*[in]*/long bBefore
                                  , /*[ref, out]*/long* pdwID );
   HRESULT (__stdcall * SetGlobalVoiceCommandsEnabled) ( IAgentCommandsEx* This
                                                       , /*[in]*/long bEnable );
   HRESULT (__stdcall * GetGlobalVoiceCommandsEnabled) ( IAgentCommandsEx* This
                                                       , /*[ref, out]*/long* pbEnabled );
} IAgentCommandsExVtbl;

struct IAgentCommandsEx {
  struct IAgentCommandsExVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentCommandsEx_GetCommandEx(This,dwCommandID,ppCommandEx) \
     (This)->lpVtbl->GetCommandEx(This,dwCommandID,ppCommandEx)
#define IAgentCommandsEx_SetDefaultID(This,dwID) \
     (This)->lpVtbl->SetDefaultID(This,dwID)
#define IAgentCommandsEx_GetDefaultID(This,pdwID) \
     (This)->lpVtbl->GetDefaultID(This,pdwID)
#define IAgentCommandsEx_SetHelpContextID(This,ulHelpID) \
     (This)->lpVtbl->SetHelpContextID(This,ulHelpID)
#define IAgentCommandsEx_GetHelpContextID(This,pulHelpID) \
     (This)->lpVtbl->GetHelpContextID(This,pulHelpID)
#define IAgentCommandsEx_SetFontName(This,bszFontName) \
     (This)->lpVtbl->SetFontName(This,bszFontName)
#define IAgentCommandsEx_GetFontName(This,pbszFontName) \
     (This)->lpVtbl->GetFontName(This,pbszFontName)
#define IAgentCommandsEx_SetFontSize(This,lFontSize) \
     (This)->lpVtbl->SetFontSize(This,lFontSize)
#define IAgentCommandsEx_GetFontSize(This,lFontSize) \
     (This)->lpVtbl->GetFontSize(This,lFontSize)
#define IAgentCommandsEx_SetVoiceCaption(This,bszVoiceCaption) \
     (This)->lpVtbl->SetVoiceCaption(This,bszVoiceCaption)
#define IAgentCommandsEx_GetVoiceCaption(This,bszVoiceCaption) \
     (This)->lpVtbl->GetVoiceCaption(This,bszVoiceCaption)
#define IAgentCommandsEx_AddEx(This,bszCaption,bszVoice,bszVoiceCaption,bEnabled,bVisible,ulHelpID,pdwID) \
     (This)->lpVtbl->AddEx(This,bszCaption,bszVoice,bszVoiceCaption,bEnabled,bVisible,ulHelpID,pdwID)
#define IAgentCommandsEx_InsertEx(This,bszCaption,bszVoice,bszVoiceCaption,bEnabled,bVisible,ulHelpID,dwRefID,bBefore,pdwID) \
     (This)->lpVtbl->InsertEx(This,bszCaption,bszVoice,bszVoiceCaption,bEnabled,bVisible,ulHelpID,dwRefID,bBefore,pdwID)
#define IAgentCommandsEx_SetGlobalVoiceCommandsEnabled(This,bEnable) \
     (This)->lpVtbl->SetGlobalVoiceCommandsEnabled(This,bEnable)
#define IAgentCommandsEx_GetGlobalVoiceCommandsEnabled(This,pbEnabled) \
     (This)->lpVtbl->GetGlobalVoiceCommandsEnabled(This,pbEnabled)
#endif /*COBJMACROS*/
typedef struct IAgentSpeechInputPropertiesVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetInstalled) ( IAgentSpeechInputProperties* This
                                      , /*[ref, out]*/long* pbInstalled );
   HRESULT (__stdcall * GetEnabled) ( IAgentSpeechInputProperties* This
                                    , /*[ref, out]*/long* pbEnabled );
   HRESULT (__stdcall * GetHotKey) ( IAgentSpeechInputProperties* This
                                   , /*[ref, out]*/BSTR* pbszHotCharKey );
   HRESULT (__stdcall * GetLCID) ( IAgentSpeechInputProperties* This
                                 , /*[ref, out]*/unsigned long* plcidCurrent );
   HRESULT (__stdcall * GetEngine) ( IAgentSpeechInputProperties* This
                                   , /*[ref, out]*/BSTR* pbszEngine );
   HRESULT (__stdcall * SetEngine) ( IAgentSpeechInputProperties* This
                                   , /*[in]*/BSTR bszEngine );
   HRESULT (__stdcall * GetListeningTip) ( IAgentSpeechInputProperties* This
                                         , /*[ref, out]*/long* pbListeningTip );
} IAgentSpeechInputPropertiesVtbl;

struct IAgentSpeechInputProperties {
  struct IAgentSpeechInputPropertiesVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentSpeechInputProperties_GetInstalled(This,pbInstalled) \
     (This)->lpVtbl->GetInstalled(This,pbInstalled)
#define IAgentSpeechInputProperties_GetEnabled(This,pbEnabled) \
     (This)->lpVtbl->GetEnabled(This,pbEnabled)
#define IAgentSpeechInputProperties_GetHotKey(This,pbszHotCharKey) \
     (This)->lpVtbl->GetHotKey(This,pbszHotCharKey)
#define IAgentSpeechInputProperties_GetLCID(This,plcidCurrent) \
     (This)->lpVtbl->GetLCID(This,plcidCurrent)
#define IAgentSpeechInputProperties_GetEngine(This,pbszEngine) \
     (This)->lpVtbl->GetEngine(This,pbszEngine)
#define IAgentSpeechInputProperties_SetEngine(This,bszEngine) \
     (This)->lpVtbl->SetEngine(This,bszEngine)
#define IAgentSpeechInputProperties_GetListeningTip(This,pbListeningTip) \
     (This)->lpVtbl->GetListeningTip(This,pbListeningTip)
#endif /*COBJMACROS*/
typedef struct IAgentAudioOutputPropertiesVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetEnabled) ( IAgentAudioOutputProperties* This
                                    , /*[ref, out]*/long* pbEnabled );
   HRESULT (__stdcall * GetUsingSoundEffects) ( IAgentAudioOutputProperties* This
                                              , /*[ref, out]*/long* pbUsingSoundEffects );
} IAgentAudioOutputPropertiesVtbl;

struct IAgentAudioOutputProperties {
  struct IAgentAudioOutputPropertiesVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentAudioOutputProperties_GetEnabled(This,pbEnabled) \
     (This)->lpVtbl->GetEnabled(This,pbEnabled)
#define IAgentAudioOutputProperties_GetUsingSoundEffects(This,pbUsingSoundEffects) \
     (This)->lpVtbl->GetUsingSoundEffects(This,pbUsingSoundEffects)
#endif /*COBJMACROS*/
typedef struct IAgentAudioOutputPropertiesExVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetStatus) ( IAgentAudioOutputPropertiesEx* This
                                   , /*[ref, out]*/long* plStatus );
} IAgentAudioOutputPropertiesExVtbl;

struct IAgentAudioOutputPropertiesEx {
  struct IAgentAudioOutputPropertiesExVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentAudioOutputPropertiesEx_GetStatus(This,plStatus) \
     (This)->lpVtbl->GetStatus(This,plStatus)
#endif /*COBJMACROS*/
typedef struct IAgentPropertySheetVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetVisible) ( IAgentPropertySheet* This
                                    , /*[ref, out]*/long* pbVisible );
   HRESULT (__stdcall * SetVisible) ( IAgentPropertySheet* This
                                    , /*[in]*/long bVisible );
   HRESULT (__stdcall * GetPosition) ( IAgentPropertySheet* This
                                     , /*[ref, out]*/long* plLeft
                                     , /*[ref, out]*/long* plTop );
   HRESULT (__stdcall * GetSize) ( IAgentPropertySheet* This
                                 , /*[ref, out]*/long* plWidth
                                 , /*[ref, out]*/long* plHeight );
   HRESULT (__stdcall * GetPage) ( IAgentPropertySheet* This
                                 , /*[ref, out]*/BSTR* pbszPage );
   HRESULT (__stdcall * SetPage) ( IAgentPropertySheet* This
                                 , /*[in]*/BSTR bszPage );
} IAgentPropertySheetVtbl;

struct IAgentPropertySheet {
  struct IAgentPropertySheetVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentPropertySheet_GetVisible(This,pbVisible) \
     (This)->lpVtbl->GetVisible(This,pbVisible)
#define IAgentPropertySheet_SetVisible(This,bVisible) \
     (This)->lpVtbl->SetVisible(This,bVisible)
#define IAgentPropertySheet_GetPosition(This,plLeft,plTop) \
     (This)->lpVtbl->GetPosition(This,plLeft,plTop)
#define IAgentPropertySheet_GetSize(This,plWidth,plHeight) \
     (This)->lpVtbl->GetSize(This,plWidth,plHeight)
#define IAgentPropertySheet_GetPage(This,pbszPage) \
     (This)->lpVtbl->GetPage(This,pbszPage)
#define IAgentPropertySheet_SetPage(This,bszPage) \
     (This)->lpVtbl->SetPage(This,bszPage)
#endif /*COBJMACROS*/
typedef struct IAgentBalloonVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetEnabled) ( IAgentBalloon* This
                                    , /*[ref, out]*/long* pbEnabled );
   HRESULT (__stdcall * GetNumLines) ( IAgentBalloon* This
                                     , /*[ref, out]*/long* plLines );
   HRESULT (__stdcall * GetNumCharsPerLine) ( IAgentBalloon* This
                                            , /*[ref, out]*/long* plCharsPerLine );
   HRESULT (__stdcall * GetFontName) ( IAgentBalloon* This
                                     , /*[ref, out]*/BSTR* pbszFontName );
   HRESULT (__stdcall * GetFontSize) ( IAgentBalloon* This
                                     , /*[ref, out]*/long* plFontSize );
   HRESULT (__stdcall * GetFontBold) ( IAgentBalloon* This
                                     , /*[ref, out]*/long* pbFontBold );
   HRESULT (__stdcall * GetFontItalic) ( IAgentBalloon* This
                                       , /*[ref, out]*/long* pbFontItalic );
   HRESULT (__stdcall * GetFontStrikethru) ( IAgentBalloon* This
                                           , /*[ref, out]*/long* pbFontStrikethru );
   HRESULT (__stdcall * GetFontUnderline) ( IAgentBalloon* This
                                          , /*[ref, out]*/long* pbFontUnderline );
   HRESULT (__stdcall * GetForeColor) ( IAgentBalloon* This
                                      , /*[ref, out]*/long* plFGColor );
   HRESULT (__stdcall * GetBackColor) ( IAgentBalloon* This
                                      , /*[ref, out]*/long* plBGColor );
   HRESULT (__stdcall * GetBorderColor) ( IAgentBalloon* This
                                        , /*[ref, out]*/long* plBorderColor );
   HRESULT (__stdcall * SetVisible) ( IAgentBalloon* This
                                    , /*[in]*/long bVisible );
   HRESULT (__stdcall * GetVisible) ( IAgentBalloon* This
                                    , /*[ref, out]*/long* pbVisible );
   HRESULT (__stdcall * SetFontName) ( IAgentBalloon* This
                                     , /*[in]*/BSTR bszFontName );
   HRESULT (__stdcall * SetFontSize) ( IAgentBalloon* This
                                     , /*[in]*/long lFontSize );
   HRESULT (__stdcall * SetFontCharSet) ( IAgentBalloon* This
                                        , /*[in]*/short sFontCharSet );
   HRESULT (__stdcall * GetFontCharSet) ( IAgentBalloon* This
                                        , /*[ref, out]*/short* psFontCharSet );
} IAgentBalloonVtbl;

struct IAgentBalloon {
  struct IAgentBalloonVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentBalloon_GetEnabled(This,pbEnabled) \
     (This)->lpVtbl->GetEnabled(This,pbEnabled)
#define IAgentBalloon_GetNumLines(This,plLines) \
     (This)->lpVtbl->GetNumLines(This,plLines)
#define IAgentBalloon_GetNumCharsPerLine(This,plCharsPerLine) \
     (This)->lpVtbl->GetNumCharsPerLine(This,plCharsPerLine)
#define IAgentBalloon_GetFontName(This,pbszFontName) \
     (This)->lpVtbl->GetFontName(This,pbszFontName)
#define IAgentBalloon_GetFontSize(This,plFontSize) \
     (This)->lpVtbl->GetFontSize(This,plFontSize)
#define IAgentBalloon_GetFontBold(This,pbFontBold) \
     (This)->lpVtbl->GetFontBold(This,pbFontBold)
#define IAgentBalloon_GetFontItalic(This,pbFontItalic) \
     (This)->lpVtbl->GetFontItalic(This,pbFontItalic)
#define IAgentBalloon_GetFontStrikethru(This,pbFontStrikethru) \
     (This)->lpVtbl->GetFontStrikethru(This,pbFontStrikethru)
#define IAgentBalloon_GetFontUnderline(This,pbFontUnderline) \
     (This)->lpVtbl->GetFontUnderline(This,pbFontUnderline)
#define IAgentBalloon_GetForeColor(This,plFGColor) \
     (This)->lpVtbl->GetForeColor(This,plFGColor)
#define IAgentBalloon_GetBackColor(This,plBGColor) \
     (This)->lpVtbl->GetBackColor(This,plBGColor)
#define IAgentBalloon_GetBorderColor(This,plBorderColor) \
     (This)->lpVtbl->GetBorderColor(This,plBorderColor)
#define IAgentBalloon_SetVisible(This,bVisible) \
     (This)->lpVtbl->SetVisible(This,bVisible)
#define IAgentBalloon_GetVisible(This,pbVisible) \
     (This)->lpVtbl->GetVisible(This,pbVisible)
#define IAgentBalloon_SetFontName(This,bszFontName) \
     (This)->lpVtbl->SetFontName(This,bszFontName)
#define IAgentBalloon_SetFontSize(This,lFontSize) \
     (This)->lpVtbl->SetFontSize(This,lFontSize)
#define IAgentBalloon_SetFontCharSet(This,sFontCharSet) \
     (This)->lpVtbl->SetFontCharSet(This,sFontCharSet)
#define IAgentBalloon_GetFontCharSet(This,psFontCharSet) \
     (This)->lpVtbl->GetFontCharSet(This,psFontCharSet)
#endif /*COBJMACROS*/
typedef struct IAgentBalloonExVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * SetStyle) ( IAgentBalloonEx* This
                                  , /*[in]*/long lStyle );
   HRESULT (__stdcall * GetStyle) ( IAgentBalloonEx* This
                                  , /*[ref, out]*/long* plStyle );
   HRESULT (__stdcall * SetNumLines) ( IAgentBalloonEx* This
                                     , /*[in]*/long lLines );
   HRESULT (__stdcall * SetNumCharsPerLine) ( IAgentBalloonEx* This
                                            , /*[in]*/long lCharsPerLine );
} IAgentBalloonExVtbl;

struct IAgentBalloonEx {
  struct IAgentBalloonExVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentBalloonEx_SetStyle(This,lStyle) \
     (This)->lpVtbl->SetStyle(This,lStyle)
#define IAgentBalloonEx_GetStyle(This,plStyle) \
     (This)->lpVtbl->GetStyle(This,plStyle)
#define IAgentBalloonEx_SetNumLines(This,lLines) \
     (This)->lpVtbl->SetNumLines(This,lLines)
#define IAgentBalloonEx_SetNumCharsPerLine(This,lCharsPerLine) \
     (This)->lpVtbl->SetNumCharsPerLine(This,lCharsPerLine)
#endif /*COBJMACROS*/
typedef struct IAgentCharacterVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetVisible) ( IAgentCharacter* This
                                    , /*[ref, out]*/long* pbVisible );
   HRESULT (__stdcall * SetPosition) ( IAgentCharacter* This
                                     , /*[in]*/long lLeft
                                     , /*[in]*/long lTop );
   HRESULT (__stdcall * GetPosition) ( IAgentCharacter* This
                                     , /*[ref, out]*/long* plLeft
                                     , /*[ref, out]*/long* plTop );
   HRESULT (__stdcall * SetSize) ( IAgentCharacter* This
                                 , /*[in]*/long lWidth
                                 , /*[in]*/long lHeight );
   HRESULT (__stdcall * GetSize) ( IAgentCharacter* This
                                 , /*[ref, out]*/long* plWidth
                                 , /*[ref, out]*/long* plHeight );
   HRESULT (__stdcall * GetName) ( IAgentCharacter* This
                                 , /*[ref, out]*/BSTR* pbszName );
   HRESULT (__stdcall * GetDescription) ( IAgentCharacter* This
                                        , /*[ref, out]*/BSTR* pbszDescription );
   HRESULT (__stdcall * GetTTSSpeed) ( IAgentCharacter* This
                                     , /*[ref, out]*/long* pdwSpeed );
   HRESULT (__stdcall * GetTTSPitch) ( IAgentCharacter* This
                                     , /*[ref, out]*/short* pwPitch );
   HRESULT (__stdcall * Activate) ( IAgentCharacter* This
                                  , /*[in]*/short sState );
   HRESULT (__stdcall * SetIdleOn) ( IAgentCharacter* This
                                   , /*[in]*/long bOn );
   HRESULT (__stdcall * GetIdleOn) ( IAgentCharacter* This
                                   , /*[ref, out]*/long* pbOn );
   HRESULT (__stdcall * Prepare) ( IAgentCharacter* This
                                 , /*[in]*/long dwType
                                 , /*[in]*/BSTR bszName
                                 , /*[in]*/long bQueue
                                 , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * Play) ( IAgentCharacter* This
                              , /*[in]*/BSTR bszAnimation
                              , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * Stop) ( IAgentCharacter* This
                              , /*[in]*/long dwReqID );
   HRESULT (__stdcall * StopAll) ( IAgentCharacter* This
                                 , /*[in]*/long lTypes );
   HRESULT (__stdcall * Wait) ( IAgentCharacter* This
                              , /*[in]*/long dwReqID
                              , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * Interrupt) ( IAgentCharacter* This
                                   , /*[in]*/long dwReqID
                                   , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * Show) ( IAgentCharacter* This
                              , /*[in]*/long bFast
                              , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * Hide) ( IAgentCharacter* This
                              , /*[in]*/long bFast
                              , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * Speak) ( IAgentCharacter* This
                               , /*[in]*/BSTR bszText
                               , /*[in]*/BSTR bszUrl
                               , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * MoveTo) ( IAgentCharacter* This
                                , /*[in]*/short x
                                , /*[in]*/short y
                                , /*[in]*/long lSpeed
                                , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * GestureAt) ( IAgentCharacter* This
                                   , /*[in]*/short x
                                   , /*[in]*/short y
                                   , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * GetMoveCause) ( IAgentCharacter* This
                                      , /*[ref, out]*/long* pdwCause );
   HRESULT (__stdcall * GetVisibilityCause) ( IAgentCharacter* This
                                            , /*[ref, out]*/long* pdwCause );
   HRESULT (__stdcall * HasOtherClients) ( IAgentCharacter* This
                                         , /*[ref, out]*/long* plNumOtherClients );
   HRESULT (__stdcall * SetSoundEffectsOn) ( IAgentCharacter* This
                                           , /*[in]*/long bOn );
   HRESULT (__stdcall * GetSoundEffectsOn) ( IAgentCharacter* This
                                           , /*[ref, out]*/long* pbOn );
   HRESULT (__stdcall * SetName) ( IAgentCharacter* This
                                 , /*[in]*/BSTR bszName );
   HRESULT (__stdcall * SetDescription) ( IAgentCharacter* This
                                        , /*[in]*/BSTR bszDescription );
   HRESULT (__stdcall * GetExtraData) ( IAgentCharacter* This
                                      , /*[ref, out]*/BSTR* pbszExtraData );
} IAgentCharacterVtbl;

struct IAgentCharacter {
  struct IAgentCharacterVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentCharacter_GetVisible(This,pbVisible) \
     (This)->lpVtbl->GetVisible(This,pbVisible)
#define IAgentCharacter_SetPosition(This,lLeft,lTop) \
     (This)->lpVtbl->SetPosition(This,lLeft,lTop)
#define IAgentCharacter_GetPosition(This,plLeft,plTop) \
     (This)->lpVtbl->GetPosition(This,plLeft,plTop)
#define IAgentCharacter_SetSize(This,lWidth,lHeight) \
     (This)->lpVtbl->SetSize(This,lWidth,lHeight)
#define IAgentCharacter_GetSize(This,plWidth,plHeight) \
     (This)->lpVtbl->GetSize(This,plWidth,plHeight)
#define IAgentCharacter_GetName(This,pbszName) \
     (This)->lpVtbl->GetName(This,pbszName)
#define IAgentCharacter_GetDescription(This,pbszDescription) \
     (This)->lpVtbl->GetDescription(This,pbszDescription)
#define IAgentCharacter_GetTTSSpeed(This,pdwSpeed) \
     (This)->lpVtbl->GetTTSSpeed(This,pdwSpeed)
#define IAgentCharacter_GetTTSPitch(This,pwPitch) \
     (This)->lpVtbl->GetTTSPitch(This,pwPitch)
#define IAgentCharacter_Activate(This,sState) \
     (This)->lpVtbl->Activate(This,sState)
#define IAgentCharacter_SetIdleOn(This,bOn) \
     (This)->lpVtbl->SetIdleOn(This,bOn)
#define IAgentCharacter_GetIdleOn(This,pbOn) \
     (This)->lpVtbl->GetIdleOn(This,pbOn)
#define IAgentCharacter_Prepare(This,dwType,bszName,bQueue,pdwReqID) \
     (This)->lpVtbl->Prepare(This,dwType,bszName,bQueue,pdwReqID)
#define IAgentCharacter_Play(This,bszAnimation,pdwReqID) \
     (This)->lpVtbl->Play(This,bszAnimation,pdwReqID)
#define IAgentCharacter_Stop(This,dwReqID) \
     (This)->lpVtbl->Stop(This,dwReqID)
#define IAgentCharacter_StopAll(This,lTypes) \
     (This)->lpVtbl->StopAll(This,lTypes)
#define IAgentCharacter_Wait(This,dwReqID,pdwReqID) \
     (This)->lpVtbl->Wait(This,dwReqID,pdwReqID)
#define IAgentCharacter_Interrupt(This,dwReqID,pdwReqID) \
     (This)->lpVtbl->Interrupt(This,dwReqID,pdwReqID)
#define IAgentCharacter_Show(This,bFast,pdwReqID) \
     (This)->lpVtbl->Show(This,bFast,pdwReqID)
#define IAgentCharacter_Hide(This,bFast,pdwReqID) \
     (This)->lpVtbl->Hide(This,bFast,pdwReqID)
#define IAgentCharacter_Speak(This,bszText,bszUrl,pdwReqID) \
     (This)->lpVtbl->Speak(This,bszText,bszUrl,pdwReqID)
#define IAgentCharacter_MoveTo(This,x,y,lSpeed,pdwReqID) \
     (This)->lpVtbl->MoveTo(This,x,y,lSpeed,pdwReqID)
#define IAgentCharacter_GestureAt(This,x,y,pdwReqID) \
     (This)->lpVtbl->GestureAt(This,x,y,pdwReqID)
#define IAgentCharacter_GetMoveCause(This,pdwCause) \
     (This)->lpVtbl->GetMoveCause(This,pdwCause)
#define IAgentCharacter_GetVisibilityCause(This,pdwCause) \
     (This)->lpVtbl->GetVisibilityCause(This,pdwCause)
#define IAgentCharacter_HasOtherClients(This,plNumOtherClients) \
     (This)->lpVtbl->HasOtherClients(This,plNumOtherClients)
#define IAgentCharacter_SetSoundEffectsOn(This,bOn) \
     (This)->lpVtbl->SetSoundEffectsOn(This,bOn)
#define IAgentCharacter_GetSoundEffectsOn(This,pbOn) \
     (This)->lpVtbl->GetSoundEffectsOn(This,pbOn)
#define IAgentCharacter_SetName(This,bszName) \
     (This)->lpVtbl->SetName(This,bszName)
#define IAgentCharacter_SetDescription(This,bszDescription) \
     (This)->lpVtbl->SetDescription(This,bszDescription)
#define IAgentCharacter_GetExtraData(This,pbszExtraData) \
     (This)->lpVtbl->GetExtraData(This,pbszExtraData)
#endif /*COBJMACROS*/
typedef struct IAgentCharacterExVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * ShowPopupMenu) ( IAgentCharacterEx* This
                                       , /*[in]*/short x
                                       , /*[in]*/short y );
   HRESULT (__stdcall * SetAutoPopupMenu) ( IAgentCharacterEx* This
                                          , /*[in]*/long bAutoPopupMenu );
   HRESULT (__stdcall * GetAutoPopupMenu) ( IAgentCharacterEx* This
                                          , /*[ref, out]*/long* pbAutoPopupMenu );
   HRESULT (__stdcall * GetHelpFileName) ( IAgentCharacterEx* This
                                         , /*[ref, out]*/BSTR* pbszName );
   HRESULT (__stdcall * SetHelpFileName) ( IAgentCharacterEx* This
                                         , /*[in]*/BSTR bszName );
   HRESULT (__stdcall * SetHelpModeOn) ( IAgentCharacterEx* This
                                       , /*[in]*/long bHelpModeOn );
   HRESULT (__stdcall * GetHelpModeOn) ( IAgentCharacterEx* This
                                       , /*[ref, out]*/long* pbHelpModeOn );
   HRESULT (__stdcall * SetHelpContextID) ( IAgentCharacterEx* This
                                          , /*[in]*/long ulID );
   HRESULT (__stdcall * GetHelpContextID) ( IAgentCharacterEx* This
                                          , /*[ref, out]*/long* pulID );
   HRESULT (__stdcall * GetActive) ( IAgentCharacterEx* This
                                   , /*[ref, out]*/short* psState );
   HRESULT (__stdcall * Listen) ( IAgentCharacterEx* This
                                , /*[in]*/long bListen );
   HRESULT (__stdcall * SetLanguageID) ( IAgentCharacterEx* This
                                       , /*[in]*/long langid );
   HRESULT (__stdcall * GetLanguageID) ( IAgentCharacterEx* This
                                       , /*[ref, out]*/long* plangid );
   HRESULT (__stdcall * GetTTSModeID) ( IAgentCharacterEx* This
                                      , /*[ref, out]*/BSTR* pbszModeID );
   HRESULT (__stdcall * SetTTSModeID) ( IAgentCharacterEx* This
                                      , /*[in]*/BSTR bszModeID );
   HRESULT (__stdcall * GetSRModeID) ( IAgentCharacterEx* This
                                     , /*[ref, out]*/BSTR* pbszModeID );
   HRESULT (__stdcall * SetSRModeID) ( IAgentCharacterEx* This
                                     , /*[in]*/BSTR bszModeID );
   HRESULT (__stdcall * GetGUID) ( IAgentCharacterEx* This
                                 , /*[ref, out]*/BSTR* pbszID );
   HRESULT (__stdcall * GetOriginalSize) ( IAgentCharacterEx* This
                                         , /*[ref, out]*/long* plWidth
                                         , /*[ref, out]*/long* plHeight );
   HRESULT (__stdcall * Think) ( IAgentCharacterEx* This
                               , /*[in]*/BSTR bszText
                               , /*[ref, out]*/long* pdwReqID );
   HRESULT (__stdcall * GetVersion) ( IAgentCharacterEx* This
                                    , /*[ref, out]*/short* psMajor
                                    , /*[ref, out]*/short* psMinor );
   HRESULT (__stdcall * GetAnimationNames) ( IAgentCharacterEx* This
                                           , /*[ref, out]*/IUnknown** punkEnum );
   HRESULT (__stdcall * GetSRStatus) ( IAgentCharacterEx* This
                                     , /*[ref, out]*/long* plStatus );
} IAgentCharacterExVtbl;

struct IAgentCharacterEx {
  struct IAgentCharacterExVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentCharacterEx_ShowPopupMenu(This,x,y) \
     (This)->lpVtbl->ShowPopupMenu(This,x,y)
#define IAgentCharacterEx_SetAutoPopupMenu(This,bAutoPopupMenu) \
     (This)->lpVtbl->SetAutoPopupMenu(This,bAutoPopupMenu)
#define IAgentCharacterEx_GetAutoPopupMenu(This,pbAutoPopupMenu) \
     (This)->lpVtbl->GetAutoPopupMenu(This,pbAutoPopupMenu)
#define IAgentCharacterEx_GetHelpFileName(This,pbszName) \
     (This)->lpVtbl->GetHelpFileName(This,pbszName)
#define IAgentCharacterEx_SetHelpFileName(This,bszName) \
     (This)->lpVtbl->SetHelpFileName(This,bszName)
#define IAgentCharacterEx_SetHelpModeOn(This,bHelpModeOn) \
     (This)->lpVtbl->SetHelpModeOn(This,bHelpModeOn)
#define IAgentCharacterEx_GetHelpModeOn(This,pbHelpModeOn) \
     (This)->lpVtbl->GetHelpModeOn(This,pbHelpModeOn)
#define IAgentCharacterEx_SetHelpContextID(This,ulID) \
     (This)->lpVtbl->SetHelpContextID(This,ulID)
#define IAgentCharacterEx_GetHelpContextID(This,pulID) \
     (This)->lpVtbl->GetHelpContextID(This,pulID)
#define IAgentCharacterEx_GetActive(This,psState) \
     (This)->lpVtbl->GetActive(This,psState)
#define IAgentCharacterEx_Listen(This,bListen) \
     (This)->lpVtbl->Listen(This,bListen)
#define IAgentCharacterEx_SetLanguageID(This,langid) \
     (This)->lpVtbl->SetLanguageID(This,langid)
#define IAgentCharacterEx_GetLanguageID(This,plangid) \
     (This)->lpVtbl->GetLanguageID(This,plangid)
#define IAgentCharacterEx_GetTTSModeID(This,pbszModeID) \
     (This)->lpVtbl->GetTTSModeID(This,pbszModeID)
#define IAgentCharacterEx_SetTTSModeID(This,bszModeID) \
     (This)->lpVtbl->SetTTSModeID(This,bszModeID)
#define IAgentCharacterEx_GetSRModeID(This,pbszModeID) \
     (This)->lpVtbl->GetSRModeID(This,pbszModeID)
#define IAgentCharacterEx_SetSRModeID(This,bszModeID) \
     (This)->lpVtbl->SetSRModeID(This,bszModeID)
#define IAgentCharacterEx_GetGUID(This,pbszID) \
     (This)->lpVtbl->GetGUID(This,pbszID)
#define IAgentCharacterEx_GetOriginalSize(This,plWidth,plHeight) \
     (This)->lpVtbl->GetOriginalSize(This,plWidth,plHeight)
#define IAgentCharacterEx_Think(This,bszText,pdwReqID) \
     (This)->lpVtbl->Think(This,bszText,pdwReqID)
#define IAgentCharacterEx_GetVersion(This,psMajor,psMinor) \
     (This)->lpVtbl->GetVersion(This,psMajor,psMinor)
#define IAgentCharacterEx_GetAnimationNames(This,punkEnum) \
     (This)->lpVtbl->GetAnimationNames(This,punkEnum)
#define IAgentCharacterEx_GetSRStatus(This,plStatus) \
     (This)->lpVtbl->GetSRStatus(This,plStatus)
#endif /*COBJMACROS*/
typedef struct IAgentExVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * GetCharacterEx) ( IAgentEx* This
                                        , /*[in]*/long dwCharID
                                        , /*[ref, out]*/IAgentCharacterEx** ppCharacterEx );
   HRESULT (__stdcall * GetVersion) ( IAgentEx* This
                                    , /*[ref, out]*/short* psMajor
                                    , /*[ref, out]*/short* psMinor );
   HRESULT (__stdcall * ShowDefaultCharacterProperties) ( IAgentEx* This
                                                        , /*[in]*/short x
                                                        , /*[in]*/short y
                                                        , /*[in]*/long bUseDefaultPosition );
} IAgentExVtbl;

struct IAgentEx {
  struct IAgentExVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentEx_GetCharacterEx(This,dwCharID,ppCharacterEx) \
     (This)->lpVtbl->GetCharacterEx(This,dwCharID,ppCharacterEx)
#define IAgentEx_GetVersion(This,psMajor,psMinor) \
     (This)->lpVtbl->GetVersion(This,psMajor,psMinor)
#define IAgentEx_ShowDefaultCharacterProperties(This,x,y,bUseDefaultPosition) \
     (This)->lpVtbl->ShowDefaultCharacterProperties(This,x,y,bUseDefaultPosition)
#endif /*COBJMACROS*/
typedef struct IAgentNotifySinkVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * Command) ( IAgentNotifySink* This
                                 , /*[in]*/long dwCommandID
                                 , /*[in]*/IUnknown* punkUserInput );
   HRESULT (__stdcall * ActivateInputState) ( IAgentNotifySink* This
                                            , /*[in]*/long dwCharID
                                            , /*[in]*/long bActivated );
   HRESULT (__stdcall * Restart) ( IAgentNotifySink* This );
   HRESULT (__stdcall * Shutdown) ( IAgentNotifySink* This );
   HRESULT (__stdcall * VisibleState) ( IAgentNotifySink* This
                                      , /*[in]*/long dwCharID
                                      , /*[in]*/long bVisible
                                      , /*[in]*/long dwCause );
   HRESULT (__stdcall * Click) ( IAgentNotifySink* This
                               , /*[in]*/long dwCharID
                               , /*[in]*/short fwKeys
                               , /*[in]*/long x
                               , /*[in]*/long y );
   HRESULT (__stdcall * DblClick) ( IAgentNotifySink* This
                                  , /*[in]*/long dwCharID
                                  , /*[in]*/short fwKeys
                                  , /*[in]*/long x
                                  , /*[in]*/long y );
   HRESULT (__stdcall * DragStart) ( IAgentNotifySink* This
                                   , /*[in]*/long dwCharID
                                   , /*[in]*/short fwKeys
                                   , /*[in]*/long x
                                   , /*[in]*/long y );
   HRESULT (__stdcall * DragComplete) ( IAgentNotifySink* This
                                      , /*[in]*/long dwCharID
                                      , /*[in]*/short fwKeys
                                      , /*[in]*/long x
                                      , /*[in]*/long y );
   HRESULT (__stdcall * RequestStart) ( IAgentNotifySink* This
                                      , /*[in]*/long dwRequestID );
   HRESULT (__stdcall * RequestComplete) ( IAgentNotifySink* This
                                         , /*[in]*/long dwRequestID
                                         , /*[in]*/long hrStatus );
   HRESULT (__stdcall * BookMark) ( IAgentNotifySink* This
                                  , /*[in]*/long dwBookMarkID );
   HRESULT (__stdcall * Idle) ( IAgentNotifySink* This
                              , /*[in]*/long dwCharID
                              , /*[in]*/long bStart );
   HRESULT (__stdcall * Move) ( IAgentNotifySink* This
                              , /*[in]*/long dwCharID
                              , /*[in]*/long x
                              , /*[in]*/long y
                              , /*[in]*/long dwCause );
   HRESULT (__stdcall * Size) ( IAgentNotifySink* This
                              , /*[in]*/long dwCharID
                              , /*[in]*/long lWidth
                              , /*[in]*/long lHeight );
   HRESULT (__stdcall * BalloonVisibleState) ( IAgentNotifySink* This
                                             , /*[in]*/long dwCharID
                                             , /*[in]*/long bVisible );
} IAgentNotifySinkVtbl;

struct IAgentNotifySink {
  struct IAgentNotifySinkVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentNotifySink_Command(This,dwCommandID,punkUserInput) \
     (This)->lpVtbl->Command(This,dwCommandID,punkUserInput)
#define IAgentNotifySink_ActivateInputState(This,dwCharID,bActivated) \
     (This)->lpVtbl->ActivateInputState(This,dwCharID,bActivated)
#define IAgentNotifySink_Restart(This) \
     (This)->lpVtbl->Restart(This)
#define IAgentNotifySink_Shutdown(This) \
     (This)->lpVtbl->Shutdown(This)
#define IAgentNotifySink_VisibleState(This,dwCharID,bVisible,dwCause) \
     (This)->lpVtbl->VisibleState(This,dwCharID,bVisible,dwCause)
#define IAgentNotifySink_Click(This,dwCharID,fwKeys,x,y) \
     (This)->lpVtbl->Click(This,dwCharID,fwKeys,x,y)
#define IAgentNotifySink_DblClick(This,dwCharID,fwKeys,x,y) \
     (This)->lpVtbl->DblClick(This,dwCharID,fwKeys,x,y)
#define IAgentNotifySink_DragStart(This,dwCharID,fwKeys,x,y) \
     (This)->lpVtbl->DragStart(This,dwCharID,fwKeys,x,y)
#define IAgentNotifySink_DragComplete(This,dwCharID,fwKeys,x,y) \
     (This)->lpVtbl->DragComplete(This,dwCharID,fwKeys,x,y)
#define IAgentNotifySink_RequestStart(This,dwRequestID) \
     (This)->lpVtbl->RequestStart(This,dwRequestID)
#define IAgentNotifySink_RequestComplete(This,dwRequestID,hrStatus) \
     (This)->lpVtbl->RequestComplete(This,dwRequestID,hrStatus)
#define IAgentNotifySink_BookMark(This,dwBookMarkID) \
     (This)->lpVtbl->BookMark(This,dwBookMarkID)
#define IAgentNotifySink_Idle(This,dwCharID,bStart) \
     (This)->lpVtbl->Idle(This,dwCharID,bStart)
#define IAgentNotifySink_Move(This,dwCharID,x,y,dwCause) \
     (This)->lpVtbl->Move(This,dwCharID,x,y,dwCause)
#define IAgentNotifySink_Size(This,dwCharID,lWidth,lHeight) \
     (This)->lpVtbl->Size(This,dwCharID,lWidth,lHeight)
#define IAgentNotifySink_BalloonVisibleState(This,dwCharID,bVisible) \
     (This)->lpVtbl->BalloonVisibleState(This,dwCharID,bVisible)
#endif /*COBJMACROS*/
typedef struct IAgentNotifySinkExVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * HelpComplete) ( IAgentNotifySinkEx* This
                                      , /*[in]*/long dwCharID
                                      , /*[in]*/long dwCommandID
                                      , /*[in]*/long dwCause );
   HRESULT (__stdcall * ListeningState) ( IAgentNotifySinkEx* This
                                        , /*[in]*/long dwCharID
                                        , /*[in]*/long bListening
                                        , /*[in]*/long dwCause );
   HRESULT (__stdcall * DefaultCharacterChange) ( IAgentNotifySinkEx* This
                                                , /*[in]*/BSTR bszGUID );
   HRESULT (__stdcall * AgentPropertyChange) ( IAgentNotifySinkEx* This );
   HRESULT (__stdcall * ActiveClientChange) ( IAgentNotifySinkEx* This
                                            , /*[in]*/long dwCharID
                                            , /*[in]*/long lStatus );
} IAgentNotifySinkExVtbl;

struct IAgentNotifySinkEx {
  struct IAgentNotifySinkExVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentNotifySinkEx_HelpComplete(This,dwCharID,dwCommandID,dwCause) \
     (This)->lpVtbl->HelpComplete(This,dwCharID,dwCommandID,dwCause)
#define IAgentNotifySinkEx_ListeningState(This,dwCharID,bListening,dwCause) \
     (This)->lpVtbl->ListeningState(This,dwCharID,bListening,dwCause)
#define IAgentNotifySinkEx_DefaultCharacterChange(This,bszGUID) \
     (This)->lpVtbl->DefaultCharacterChange(This,bszGUID)
#define IAgentNotifySinkEx_AgentPropertyChange(This) \
     (This)->lpVtbl->AgentPropertyChange(This)
#define IAgentNotifySinkEx_ActiveClientChange(This,dwCharID,lStatus) \
     (This)->lpVtbl->ActiveClientChange(This,dwCharID,lStatus)
#endif /*COBJMACROS*/
typedef struct IAgentCommandWindowVtbl {
   void* reserved0;
   void* reserved1;
   void* reserved2;
   void* reserved3;
   void* reserved4;
   void* reserved5;
   void* reserved6;
   HRESULT (__stdcall * SetVisible) ( IAgentCommandWindow* This
                                    , /*[in]*/long bVisible );
   HRESULT (__stdcall * GetVisible) ( IAgentCommandWindow* This
                                    , /*[ref, out]*/long* pbVisible );
   HRESULT (__stdcall * GetPosition) ( IAgentCommandWindow* This
                                     , /*[ref, out]*/long* plLeft
                                     , /*[ref, out]*/long* plTop );
   HRESULT (__stdcall * GetSize) ( IAgentCommandWindow* This
                                 , /*[ref, out]*/long* plWidth
                                 , /*[ref, out]*/long* plHeight );
} IAgentCommandWindowVtbl;

struct IAgentCommandWindow {
  struct IAgentCommandWindowVtbl *lpVtbl;
  };
#ifdef COBJMACROS
#define IAgentCommandWindow_SetVisible(This,bVisible) \
     (This)->lpVtbl->SetVisible(This,bVisible)
#define IAgentCommandWindow_GetVisible(This,pbVisible) \
     (This)->lpVtbl->GetVisible(This,pbVisible)
#define IAgentCommandWindow_GetPosition(This,plLeft,plTop) \
     (This)->lpVtbl->GetPosition(This,plLeft,plTop)
#define IAgentCommandWindow_GetSize(This,plWidth,plHeight) \
     (This)->lpVtbl->GetSize(This,plWidth,plHeight)
#endif /*COBJMACROS*/
/*};*/

#endif
