/*
Automatically generated by HaskellDirect (ihc.exe), version 0.21
Created: 12:42 Paris, Madrid (heure d’été), Thursday 09 August, 2012
Command line: -o MSWord.hs -d -dshow-passes --verbose -fgen-variant-instances -fno-qualified-names -fno-export-list MSWORD.IDL
*/


#ifndef __INT64_DEFINED__
#ifdef __GNUC__
typedef long long int64;
typedef unsigned long long uint64;
#else
#ifdef _MSC_VER
typedef __int64 int64;
typedef unsigned __int64 uint64;
#else
/* Need some help here, please. */
#endif
#endif
#define __INT64_DEFINED__
#endif


typedef long (__stdcall * prim_Word_setFeatureInstall__funptr) (void* arg1, MsoFeatureInstall arg2);
long prim_Word_setFeatureInstall (void* arg0, void* arg1, MsoFeatureInstall* arg2)
{
long res;
prim_Word_setFeatureInstall__funptr __funptr__;
__funptr__ = (prim_Word_setFeatureInstall__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setAutomationSecurity__funptr) (void* arg1, MsoAutomationSecurity arg2);
long prim_Word_setAutomationSecurity (void* arg0, void* arg1, MsoAutomationSecurity* arg2)
{
long res;
prim_Word_setAutomationSecurity__funptr __funptr__;
__funptr__ = (prim_Word_setAutomationSecurity__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_getFileDialog__funptr) (void* arg1, MsoFileDialogType arg2, void* arg3);
long prim_Word_getFileDialog (void* arg0, void* arg1, MsoFileDialogType* arg2, void* arg3)
{
long res;
prim_Word_getFileDialog__funptr __funptr__;
__funptr__ = (prim_Word_getFileDialog__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3);
return (res);
}
typedef long (__stdcall * prim_Word_reloadAs__funptr) (void* arg1, MsoEncoding arg2);
long prim_Word_reloadAs (void* arg0, void* arg1, MsoEncoding* arg2)
{
long res;
prim_Word_reloadAs__funptr __funptr__;
__funptr__ = (prim_Word_reloadAs__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setSaveEncoding__funptr) (void* arg1, MsoEncoding arg2);
long prim_Word_setSaveEncoding (void* arg0, void* arg1, MsoEncoding* arg2)
{
long res;
prim_Word_setSaveEncoding__funptr __funptr__;
__funptr__ = (prim_Word_setSaveEncoding__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setTextEncoding__funptr) (void* arg1, MsoEncoding arg2);
long prim_Word_setTextEncoding (void* arg0, void* arg1, MsoEncoding* arg2)
{
long res;
prim_Word_setTextEncoding__funptr __funptr__;
__funptr__ = (prim_Word_setTextEncoding__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_addCallout__funptr) (void* arg1, MsoCalloutType arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8);
long prim_Word_addCallout (void* arg0, void* arg1, MsoCalloutType* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8)
{
long res;
prim_Word_addCallout__funptr __funptr__;
__funptr__ = (prim_Word_addCallout__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7, arg8);
return (res);
}
typedef long (__stdcall * prim_Word_addConnector__funptr) (void* arg1, MsoConnectorType arg2, float arg3, float arg4, float arg5, float arg6, void* arg7);
long prim_Word_addConnector (void* arg0, void* arg1, MsoConnectorType* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7)
{
long res;
prim_Word_addConnector__funptr __funptr__;
__funptr__ = (prim_Word_addConnector__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7);
return (res);
}
typedef long (__stdcall * prim_Word_addLabel__funptr) (void* arg1, MsoTextOrientation arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8);
long prim_Word_addLabel (void* arg0, void* arg1, MsoTextOrientation* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8)
{
long res;
prim_Word_addLabel__funptr __funptr__;
__funptr__ = (prim_Word_addLabel__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7, arg8);
return (res);
}
typedef long (__stdcall * prim_Word_addTextEffect__funptr) (void* arg1, MsoPresetTextEffect arg2, void* arg3, void* arg4, float arg5, MsoTriState arg6, MsoTriState arg7, float arg8, float arg9, void* arg10, void* arg11);
long prim_Word_addTextEffect (void* arg0, void* arg1, MsoPresetTextEffect* arg2, void* arg3, void* arg4, float arg5, MsoTriState* arg6, MsoTriState* arg7, float arg8, float arg9, void* arg10, void* arg11)
{
long res;
prim_Word_addTextEffect__funptr __funptr__;
__funptr__ = (prim_Word_addTextEffect__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, *arg6, *arg7, arg8, arg9, arg10, arg11);
return (res);
}
typedef long (__stdcall * prim_Word_addTextbox__funptr) (void* arg1, MsoTextOrientation arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8);
long prim_Word_addTextbox (void* arg0, void* arg1, MsoTextOrientation* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8)
{
long res;
prim_Word_addTextbox__funptr __funptr__;
__funptr__ = (prim_Word_addTextbox__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7, arg8);
return (res);
}
typedef long (__stdcall * prim_Word_buildFreeform__funptr) (void* arg1, MsoEditingType arg2, float arg3, float arg4, void* arg5);
long prim_Word_buildFreeform (void* arg0, void* arg1, MsoEditingType* arg2, float arg3, float arg4, void* arg5)
{
long res;
prim_Word_buildFreeform__funptr __funptr__;
__funptr__ = (prim_Word_buildFreeform__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5);
return (res);
}
typedef long (__stdcall * prim_Word_addDiagram__funptr) (void* arg1, MsoDiagramType arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8);
long prim_Word_addDiagram (void* arg0, void* arg1, MsoDiagramType* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7, void* arg8)
{
long res;
prim_Word_addDiagram__funptr __funptr__;
__funptr__ = (prim_Word_addDiagram__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7, arg8);
return (res);
}
typedef long (__stdcall * prim_Word_addChart__funptr) (void* arg1, XlChartType arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* arg7, void* arg8);
long prim_Word_addChart (void* arg0, void* arg1, XlChartType* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* arg7, void* arg8)
{
long res;
prim_Word_addChart__funptr __funptr__;
__funptr__ = (prim_Word_addChart__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7, arg8);
return (res);
}
typedef long (__stdcall * prim_Word_setAutoShapeType__funptr) (void* arg1, MsoAutoShapeType arg2);
long prim_Word_setAutoShapeType (void* arg0, void* arg1, MsoAutoShapeType* arg2)
{
long res;
prim_Word_setAutoShapeType__funptr __funptr__;
__funptr__ = (prim_Word_setAutoShapeType__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setLockAspectRatio__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setLockAspectRatio (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setLockAspectRatio__funptr __funptr__;
__funptr__ = (prim_Word_setLockAspectRatio__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setVisible3__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setVisible3 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setVisible3__funptr __funptr__;
__funptr__ = (prim_Word_setVisible3__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_align__funptr) (void* arg1, MsoAlignCmd arg2, long arg3);
long prim_Word_align (void* arg0, void* arg1, MsoAlignCmd* arg2, long arg3)
{
long res;
prim_Word_align__funptr __funptr__;
__funptr__ = (prim_Word_align__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3);
return (res);
}
typedef long (__stdcall * prim_Word_distribute__funptr) (void* arg1, MsoDistributeCmd arg2, long arg3);
long prim_Word_distribute (void* arg0, void* arg1, MsoDistributeCmd* arg2, long arg3)
{
long res;
prim_Word_distribute__funptr __funptr__;
__funptr__ = (prim_Word_distribute__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3);
return (res);
}
typedef long (__stdcall * prim_Word_flip__funptr) (void* arg1, MsoFlipCmd arg2);
long prim_Word_flip (void* arg0, void* arg1, MsoFlipCmd* arg2)
{
long res;
prim_Word_flip__funptr __funptr__;
__funptr__ = (prim_Word_flip__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_scaleHeight__funptr) (void* arg1, float arg2, MsoTriState arg3, MsoScaleFrom arg4);
long prim_Word_scaleHeight (void* arg0, void* arg1, float arg2, MsoTriState* arg3, MsoScaleFrom* arg4)
{
long res;
prim_Word_scaleHeight__funptr __funptr__;
__funptr__ = (prim_Word_scaleHeight__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3, *arg4);
return (res);
}
typedef long (__stdcall * prim_Word_scaleWidth__funptr) (void* arg1, float arg2, MsoTriState arg3, MsoScaleFrom arg4);
long prim_Word_scaleWidth (void* arg0, void* arg1, float arg2, MsoTriState* arg3, MsoScaleFrom* arg4)
{
long res;
prim_Word_scaleWidth__funptr __funptr__;
__funptr__ = (prim_Word_scaleWidth__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3, *arg4);
return (res);
}
typedef long (__stdcall * prim_Word_zOrder__funptr) (void* arg1, MsoZOrderCmd arg2);
long prim_Word_zOrder (void* arg0, void* arg1, MsoZOrderCmd* arg2)
{
long res;
prim_Word_zOrder__funptr __funptr__;
__funptr__ = (prim_Word_zOrder__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setAutoShapeType0__funptr) (void* arg1, MsoAutoShapeType arg2);
long prim_Word_setAutoShapeType0 (void* arg0, void* arg1, MsoAutoShapeType* arg2)
{
long res;
prim_Word_setAutoShapeType0__funptr __funptr__;
__funptr__ = (prim_Word_setAutoShapeType0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setLockAspectRatio0__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setLockAspectRatio0 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setLockAspectRatio0__funptr __funptr__;
__funptr__ = (prim_Word_setLockAspectRatio0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setVisible4__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setVisible4 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setVisible4__funptr __funptr__;
__funptr__ = (prim_Word_setVisible4__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_flip0__funptr) (void* arg1, MsoFlipCmd arg2);
long prim_Word_flip0 (void* arg0, void* arg1, MsoFlipCmd* arg2)
{
long res;
prim_Word_flip0__funptr __funptr__;
__funptr__ = (prim_Word_flip0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_scaleHeight0__funptr) (void* arg1, float arg2, MsoTriState arg3, MsoScaleFrom arg4);
long prim_Word_scaleHeight0 (void* arg0, void* arg1, float arg2, MsoTriState* arg3, MsoScaleFrom* arg4)
{
long res;
prim_Word_scaleHeight0__funptr __funptr__;
__funptr__ = (prim_Word_scaleHeight0__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3, *arg4);
return (res);
}
typedef long (__stdcall * prim_Word_scaleWidth0__funptr) (void* arg1, float arg2, MsoTriState arg3, MsoScaleFrom arg4);
long prim_Word_scaleWidth0 (void* arg0, void* arg1, float arg2, MsoTriState* arg3, MsoScaleFrom* arg4)
{
long res;
prim_Word_scaleWidth0__funptr __funptr__;
__funptr__ = (prim_Word_scaleWidth0__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3, *arg4);
return (res);
}
typedef long (__stdcall * prim_Word_zOrder0__funptr) (void* arg1, MsoZOrderCmd arg2);
long prim_Word_zOrder0 (void* arg0, void* arg1, MsoZOrderCmd* arg2)
{
long res;
prim_Word_zOrder0__funptr __funptr__;
__funptr__ = (prim_Word_zOrder0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setOrientation2__funptr) (void* arg1, MsoTextOrientation arg2);
long prim_Word_setOrientation2 (void* arg0, void* arg1, MsoTextOrientation* arg2)
{
long res;
prim_Word_setOrientation2__funptr __funptr__;
__funptr__ = (prim_Word_setOrientation2__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setVerticalAnchor__funptr) (void* arg1, MsoVerticalAnchor arg2);
long prim_Word_setVerticalAnchor (void* arg0, void* arg1, MsoVerticalAnchor* arg2)
{
long res;
prim_Word_setVerticalAnchor__funptr __funptr__;
__funptr__ = (prim_Word_setVerticalAnchor__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setLockAspectRatio1__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setLockAspectRatio1 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setLockAspectRatio1__funptr __funptr__;
__funptr__ = (prim_Word_setLockAspectRatio1__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_addChart0__funptr) (void* arg1, XlChartType arg2, void* arg3, void* arg4);
long prim_Word_addChart0 (void* arg0, void* arg1, XlChartType* arg2, void* arg3, void* arg4)
{
long res;
prim_Word_addChart0__funptr __funptr__;
__funptr__ = (prim_Word_addChart0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4);
return (res);
}
typedef long (__stdcall * prim_Word_setDefaultTextEncoding__funptr) (void* arg1, MsoEncoding arg2);
long prim_Word_setDefaultTextEncoding (void* arg0, void* arg1, MsoEncoding* arg2)
{
long res;
prim_Word_setDefaultTextEncoding__funptr __funptr__;
__funptr__ = (prim_Word_setDefaultTextEncoding__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setAccent__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setAccent (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setAccent__funptr __funptr__;
__funptr__ = (prim_Word_setAccent__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setAngle__funptr) (void* arg1, MsoCalloutAngleType arg2);
long prim_Word_setAngle (void* arg0, void* arg1, MsoCalloutAngleType* arg2)
{
long res;
prim_Word_setAngle__funptr __funptr__;
__funptr__ = (prim_Word_setAngle__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setAutoAttach__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setAutoAttach (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setAutoAttach__funptr __funptr__;
__funptr__ = (prim_Word_setAutoAttach__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setBorder__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setBorder (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setBorder__funptr __funptr__;
__funptr__ = (prim_Word_setBorder__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setType2__funptr) (void* arg1, MsoCalloutType arg2);
long prim_Word_setType2 (void* arg0, void* arg1, MsoCalloutType* arg2)
{
long res;
prim_Word_setType2__funptr __funptr__;
__funptr__ = (prim_Word_setType2__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_presetDrop__funptr) (void* arg1, MsoCalloutDropType arg2);
long prim_Word_presetDrop (void* arg0, void* arg1, MsoCalloutDropType* arg2)
{
long res;
prim_Word_presetDrop__funptr __funptr__;
__funptr__ = (prim_Word_presetDrop__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setOverPrint__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setOverPrint (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setOverPrint__funptr __funptr__;
__funptr__ = (prim_Word_setOverPrint__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setType3__funptr) (void* arg1, MsoConnectorType arg2);
long prim_Word_setType3 (void* arg0, void* arg1, MsoConnectorType* arg2)
{
long res;
prim_Word_setType3__funptr __funptr__;
__funptr__ = (prim_Word_setType3__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setVisible5__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setVisible5 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setVisible5__funptr __funptr__;
__funptr__ = (prim_Word_setVisible5__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_oneColorGradient__funptr) (void* arg1, MsoGradientStyle arg2, long arg3, float arg4);
long prim_Word_oneColorGradient (void* arg0, void* arg1, MsoGradientStyle* arg2, long arg3, float arg4)
{
long res;
prim_Word_oneColorGradient__funptr __funptr__;
__funptr__ = (prim_Word_oneColorGradient__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4);
return (res);
}
typedef long (__stdcall * prim_Word_patterned__funptr) (void* arg1, MsoPatternType arg2);
long prim_Word_patterned (void* arg0, void* arg1, MsoPatternType* arg2)
{
long res;
prim_Word_patterned__funptr __funptr__;
__funptr__ = (prim_Word_patterned__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_presetGradient__funptr) (void* arg1, MsoGradientStyle arg2, long arg3, MsoPresetGradientType arg4);
long prim_Word_presetGradient (void* arg0, void* arg1, MsoGradientStyle* arg2, long arg3, MsoPresetGradientType* arg4)
{
long res;
prim_Word_presetGradient__funptr __funptr__;
__funptr__ = (prim_Word_presetGradient__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, *arg4);
return (res);
}
typedef long (__stdcall * prim_Word_presetTextured__funptr) (void* arg1, MsoPresetTexture arg2);
long prim_Word_presetTextured (void* arg0, void* arg1, MsoPresetTexture* arg2)
{
long res;
prim_Word_presetTextured__funptr __funptr__;
__funptr__ = (prim_Word_presetTextured__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_twoColorGradient__funptr) (void* arg1, MsoGradientStyle arg2, long arg3);
long prim_Word_twoColorGradient (void* arg0, void* arg1, MsoGradientStyle* arg2, long arg3)
{
long res;
prim_Word_twoColorGradient__funptr __funptr__;
__funptr__ = (prim_Word_twoColorGradient__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3);
return (res);
}
typedef long (__stdcall * prim_Word_addNodes__funptr) (void* arg1, MsoSegmentType arg2, MsoEditingType arg3, float arg4, float arg5, float arg6, float arg7, float arg8, float arg9);
long prim_Word_addNodes (void* arg0, void* arg1, MsoSegmentType* arg2, MsoEditingType* arg3, float arg4, float arg5, float arg6, float arg7, float arg8, float arg9)
{
long res;
prim_Word_addNodes__funptr __funptr__;
__funptr__ = (prim_Word_addNodes__funptr)arg0;
res =__funptr__(arg1, *arg2, *arg3, arg4, arg5, arg6, arg7, arg8, arg9);
return (res);
}
typedef long (__stdcall * prim_Word_setBeginArrowheadLength__funptr) (void* arg1, MsoArrowheadLength arg2);
long prim_Word_setBeginArrowheadLength (void* arg0, void* arg1, MsoArrowheadLength* arg2)
{
long res;
prim_Word_setBeginArrowheadLength__funptr __funptr__;
__funptr__ = (prim_Word_setBeginArrowheadLength__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setBeginArrowheadStyle__funptr) (void* arg1, MsoArrowheadStyle arg2);
long prim_Word_setBeginArrowheadStyle (void* arg0, void* arg1, MsoArrowheadStyle* arg2)
{
long res;
prim_Word_setBeginArrowheadStyle__funptr __funptr__;
__funptr__ = (prim_Word_setBeginArrowheadStyle__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setBeginArrowheadWidth__funptr) (void* arg1, MsoArrowheadWidth arg2);
long prim_Word_setBeginArrowheadWidth (void* arg0, void* arg1, MsoArrowheadWidth* arg2)
{
long res;
prim_Word_setBeginArrowheadWidth__funptr __funptr__;
__funptr__ = (prim_Word_setBeginArrowheadWidth__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setDashStyle__funptr) (void* arg1, MsoLineDashStyle arg2);
long prim_Word_setDashStyle (void* arg0, void* arg1, MsoLineDashStyle* arg2)
{
long res;
prim_Word_setDashStyle__funptr __funptr__;
__funptr__ = (prim_Word_setDashStyle__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setEndArrowheadLength__funptr) (void* arg1, MsoArrowheadLength arg2);
long prim_Word_setEndArrowheadLength (void* arg0, void* arg1, MsoArrowheadLength* arg2)
{
long res;
prim_Word_setEndArrowheadLength__funptr __funptr__;
__funptr__ = (prim_Word_setEndArrowheadLength__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setEndArrowheadStyle__funptr) (void* arg1, MsoArrowheadStyle arg2);
long prim_Word_setEndArrowheadStyle (void* arg0, void* arg1, MsoArrowheadStyle* arg2)
{
long res;
prim_Word_setEndArrowheadStyle__funptr __funptr__;
__funptr__ = (prim_Word_setEndArrowheadStyle__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setEndArrowheadWidth__funptr) (void* arg1, MsoArrowheadWidth arg2);
long prim_Word_setEndArrowheadWidth (void* arg0, void* arg1, MsoArrowheadWidth* arg2)
{
long res;
prim_Word_setEndArrowheadWidth__funptr __funptr__;
__funptr__ = (prim_Word_setEndArrowheadWidth__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPattern__funptr) (void* arg1, MsoPatternType arg2);
long prim_Word_setPattern (void* arg0, void* arg1, MsoPatternType* arg2)
{
long res;
prim_Word_setPattern__funptr __funptr__;
__funptr__ = (prim_Word_setPattern__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setStyle8__funptr) (void* arg1, MsoLineStyle arg2);
long prim_Word_setStyle8 (void* arg0, void* arg1, MsoLineStyle* arg2)
{
long res;
prim_Word_setStyle8__funptr __funptr__;
__funptr__ = (prim_Word_setStyle8__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setVisible6__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setVisible6 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setVisible6__funptr __funptr__;
__funptr__ = (prim_Word_setVisible6__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setInsetPen__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setInsetPen (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setInsetPen__funptr __funptr__;
__funptr__ = (prim_Word_setInsetPen__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setColorType__funptr) (void* arg1, MsoPictureColorType arg2);
long prim_Word_setColorType (void* arg0, void* arg1, MsoPictureColorType* arg2)
{
long res;
prim_Word_setColorType__funptr __funptr__;
__funptr__ = (prim_Word_setColorType__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setTransparentBackground__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setTransparentBackground (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setTransparentBackground__funptr __funptr__;
__funptr__ = (prim_Word_setTransparentBackground__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setObscured__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setObscured (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setObscured__funptr __funptr__;
__funptr__ = (prim_Word_setObscured__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setType4__funptr) (void* arg1, MsoShadowType arg2);
long prim_Word_setType4 (void* arg0, void* arg1, MsoShadowType* arg2)
{
long res;
prim_Word_setType4__funptr __funptr__;
__funptr__ = (prim_Word_setType4__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setVisible7__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setVisible7 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setVisible7__funptr __funptr__;
__funptr__ = (prim_Word_setVisible7__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setStyle9__funptr) (void* arg1, MsoShadowStyle arg2);
long prim_Word_setStyle9 (void* arg0, void* arg1, MsoShadowStyle* arg2)
{
long res;
prim_Word_setStyle9__funptr __funptr__;
__funptr__ = (prim_Word_setStyle9__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setRotateWithShape__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setRotateWithShape (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setRotateWithShape__funptr __funptr__;
__funptr__ = (prim_Word_setRotateWithShape__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setEditingType__funptr) (void* arg1, long arg2, MsoEditingType arg3);
long prim_Word_setEditingType (void* arg0, void* arg1, long arg2, MsoEditingType* arg3)
{
long res;
prim_Word_setEditingType__funptr __funptr__;
__funptr__ = (prim_Word_setEditingType__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3);
return (res);
}
typedef long (__stdcall * prim_Word_setSegmentType__funptr) (void* arg1, long arg2, MsoSegmentType arg3);
long prim_Word_setSegmentType (void* arg0, void* arg1, long arg2, MsoSegmentType* arg3)
{
long res;
prim_Word_setSegmentType__funptr __funptr__;
__funptr__ = (prim_Word_setSegmentType__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3);
return (res);
}
typedef long (__stdcall * prim_Word_insert1__funptr) (void* arg1, long arg2, MsoSegmentType arg3, MsoEditingType arg4, float arg5, float arg6, float arg7, float arg8, float arg9, float arg10);
long prim_Word_insert1 (void* arg0, void* arg1, long arg2, MsoSegmentType* arg3, MsoEditingType* arg4, float arg5, float arg6, float arg7, float arg8, float arg9, float arg10)
{
long res;
prim_Word_insert1__funptr __funptr__;
__funptr__ = (prim_Word_insert1__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3, *arg4, arg5, arg6, arg7, arg8, arg9, arg10);
return (res);
}
typedef long (__stdcall * prim_Word_setAlignment7__funptr) (void* arg1, MsoTextEffectAlignment arg2);
long prim_Word_setAlignment7 (void* arg0, void* arg1, MsoTextEffectAlignment* arg2)
{
long res;
prim_Word_setAlignment7__funptr __funptr__;
__funptr__ = (prim_Word_setAlignment7__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setFontBold__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setFontBold (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setFontBold__funptr __funptr__;
__funptr__ = (prim_Word_setFontBold__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setFontItalic__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setFontItalic (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setFontItalic__funptr __funptr__;
__funptr__ = (prim_Word_setFontItalic__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setKernedPairs__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setKernedPairs (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setKernedPairs__funptr __funptr__;
__funptr__ = (prim_Word_setKernedPairs__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setNormalizedHeight__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setNormalizedHeight (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setNormalizedHeight__funptr __funptr__;
__funptr__ = (prim_Word_setNormalizedHeight__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPresetShape__funptr) (void* arg1, MsoPresetTextEffectShape arg2);
long prim_Word_setPresetShape (void* arg0, void* arg1, MsoPresetTextEffectShape* arg2)
{
long res;
prim_Word_setPresetShape__funptr __funptr__;
__funptr__ = (prim_Word_setPresetShape__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPresetTextEffect__funptr) (void* arg1, MsoPresetTextEffect arg2);
long prim_Word_setPresetTextEffect (void* arg0, void* arg1, MsoPresetTextEffect* arg2)
{
long res;
prim_Word_setPresetTextEffect__funptr __funptr__;
__funptr__ = (prim_Word_setPresetTextEffect__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setRotatedChars__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setRotatedChars (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setRotatedChars__funptr __funptr__;
__funptr__ = (prim_Word_setRotatedChars__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setExtrusionColorType__funptr) (void* arg1, MsoExtrusionColorType arg2);
long prim_Word_setExtrusionColorType (void* arg0, void* arg1, MsoExtrusionColorType* arg2)
{
long res;
prim_Word_setExtrusionColorType__funptr __funptr__;
__funptr__ = (prim_Word_setExtrusionColorType__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPerspective__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setPerspective (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setPerspective__funptr __funptr__;
__funptr__ = (prim_Word_setPerspective__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPresetLightingDirection__funptr) (void* arg1, MsoPresetLightingDirection arg2);
long prim_Word_setPresetLightingDirection (void* arg0, void* arg1, MsoPresetLightingDirection* arg2)
{
long res;
prim_Word_setPresetLightingDirection__funptr __funptr__;
__funptr__ = (prim_Word_setPresetLightingDirection__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPresetLightingSoftness__funptr) (void* arg1, MsoPresetLightingSoftness arg2);
long prim_Word_setPresetLightingSoftness (void* arg0, void* arg1, MsoPresetLightingSoftness* arg2)
{
long res;
prim_Word_setPresetLightingSoftness__funptr __funptr__;
__funptr__ = (prim_Word_setPresetLightingSoftness__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPresetMaterial__funptr) (void* arg1, MsoPresetMaterial arg2);
long prim_Word_setPresetMaterial (void* arg0, void* arg1, MsoPresetMaterial* arg2)
{
long res;
prim_Word_setPresetMaterial__funptr __funptr__;
__funptr__ = (prim_Word_setPresetMaterial__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setVisible8__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setVisible8 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setVisible8__funptr __funptr__;
__funptr__ = (prim_Word_setVisible8__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setExtrusionDirection__funptr) (void* arg1, MsoPresetExtrusionDirection arg2);
long prim_Word_setExtrusionDirection (void* arg0, void* arg1, MsoPresetExtrusionDirection* arg2)
{
long res;
prim_Word_setExtrusionDirection__funptr __funptr__;
__funptr__ = (prim_Word_setExtrusionDirection__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setThreeDFormat__funptr) (void* arg1, MsoPresetThreeDFormat arg2);
long prim_Word_setThreeDFormat (void* arg0, void* arg1, MsoPresetThreeDFormat* arg2)
{
long res;
prim_Word_setThreeDFormat__funptr __funptr__;
__funptr__ = (prim_Word_setThreeDFormat__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPresetCamera__funptr) (void* arg1, MsoPresetCamera arg2);
long prim_Word_setPresetCamera (void* arg0, void* arg1, MsoPresetCamera* arg2)
{
long res;
prim_Word_setPresetCamera__funptr __funptr__;
__funptr__ = (prim_Word_setPresetCamera__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setPresetLighting__funptr) (void* arg1, MsoLightRigType arg2);
long prim_Word_setPresetLighting (void* arg0, void* arg1, MsoLightRigType* arg2)
{
long res;
prim_Word_setPresetLighting__funptr __funptr__;
__funptr__ = (prim_Word_setPresetLighting__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setBevelTopType__funptr) (void* arg1, MsoBevelType arg2);
long prim_Word_setBevelTopType (void* arg0, void* arg1, MsoBevelType* arg2)
{
long res;
prim_Word_setBevelTopType__funptr __funptr__;
__funptr__ = (prim_Word_setBevelTopType__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setBevelBottomType__funptr) (void* arg1, MsoBevelType arg2);
long prim_Word_setBevelBottomType (void* arg0, void* arg1, MsoBevelType* arg2)
{
long res;
prim_Word_setBevelBottomType__funptr __funptr__;
__funptr__ = (prim_Word_setBevelBottomType__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setProjectText__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setProjectText (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setProjectText__funptr __funptr__;
__funptr__ = (prim_Word_setProjectText__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setScreenSize__funptr) (void* arg1, MsoScreenSize arg2);
long prim_Word_setScreenSize (void* arg0, void* arg1, MsoScreenSize* arg2)
{
long res;
prim_Word_setScreenSize__funptr __funptr__;
__funptr__ = (prim_Word_setScreenSize__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setEncoding__funptr) (void* arg1, MsoEncoding arg2);
long prim_Word_setEncoding (void* arg0, void* arg1, MsoEncoding* arg2)
{
long res;
prim_Word_setEncoding__funptr __funptr__;
__funptr__ = (prim_Word_setEncoding__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setTargetBrowser__funptr) (void* arg1, MsoTargetBrowser arg2);
long prim_Word_setTargetBrowser (void* arg0, void* arg1, MsoTargetBrowser* arg2)
{
long res;
prim_Word_setTargetBrowser__funptr __funptr__;
__funptr__ = (prim_Word_setTargetBrowser__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setScreenSize0__funptr) (void* arg1, MsoScreenSize arg2);
long prim_Word_setScreenSize0 (void* arg0, void* arg1, MsoScreenSize* arg2)
{
long res;
prim_Word_setScreenSize0__funptr __funptr__;
__funptr__ = (prim_Word_setScreenSize0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setEncoding0__funptr) (void* arg1, MsoEncoding arg2);
long prim_Word_setEncoding0 (void* arg0, void* arg1, MsoEncoding* arg2)
{
long res;
prim_Word_setEncoding0__funptr __funptr__;
__funptr__ = (prim_Word_setEncoding0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setTargetBrowser0__funptr) (void* arg1, MsoTargetBrowser arg2);
long prim_Word_setTargetBrowser0 (void* arg0, void* arg1, MsoTargetBrowser* arg2)
{
long res;
prim_Word_setTargetBrowser0__funptr __funptr__;
__funptr__ = (prim_Word_setTargetBrowser0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setLayout__funptr) (void* arg1, MsoOrgChartLayoutType arg2);
long prim_Word_setLayout (void* arg0, void* arg1, MsoOrgChartLayoutType* arg2)
{
long res;
prim_Word_setLayout__funptr __funptr__;
__funptr__ = (prim_Word_setLayout__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_addNode__funptr) (void* arg1, MsoRelativeNodePosition arg2, MsoDiagramNodeType arg3, void* arg4);
long prim_Word_addNode (void* arg0, void* arg1, MsoRelativeNodePosition* arg2, MsoDiagramNodeType* arg3, void* arg4)
{
long res;
prim_Word_addNode__funptr __funptr__;
__funptr__ = (prim_Word_addNode__funptr)arg0;
res =__funptr__(arg1, *arg2, *arg3, arg4);
return (res);
}
typedef long (__stdcall * prim_Word_moveNode__funptr) (void* arg1, void* arg2, MsoRelativeNodePosition arg3);
long prim_Word_moveNode (void* arg0, void* arg1, void* arg2, MsoRelativeNodePosition* arg3)
{
long res;
prim_Word_moveNode__funptr __funptr__;
__funptr__ = (prim_Word_moveNode__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3);
return (res);
}
typedef long (__stdcall * prim_Word_swapNode__funptr) (void* arg1, void* arg2, MsoRelativeNodePosition arg3);
long prim_Word_swapNode (void* arg0, void* arg1, void* arg2, MsoRelativeNodePosition* arg3)
{
long res;
prim_Word_swapNode__funptr __funptr__;
__funptr__ = (prim_Word_swapNode__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3);
return (res);
}
typedef long (__stdcall * prim_Word_cloneNode__funptr) (void* arg1, VARIANT_BOOL arg2, void* arg3, MsoRelativeNodePosition arg4, void* arg5);
long prim_Word_cloneNode (void* arg0, void* arg1, VARIANT_BOOL arg2, void* arg3, MsoRelativeNodePosition* arg4, void* arg5)
{
long res;
prim_Word_cloneNode__funptr __funptr__;
__funptr__ = (prim_Word_cloneNode__funptr)arg0;
res =__funptr__(arg1, arg2, arg3, *arg4, arg5);
return (res);
}
typedef long (__stdcall * prim_Word_addNode0__funptr) (void* arg1, void* arg2, MsoDiagramNodeType arg3, void* arg4);
long prim_Word_addNode0 (void* arg0, void* arg1, void* arg2, MsoDiagramNodeType* arg3, void* arg4)
{
long res;
prim_Word_addNode0__funptr __funptr__;
__funptr__ = (prim_Word_addNode0__funptr)arg0;
res =__funptr__(arg1, arg2, *arg3, arg4);
return (res);
}
typedef long (__stdcall * prim_Word_setAutoLayout__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setAutoLayout (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setAutoLayout__funptr __funptr__;
__funptr__ = (prim_Word_setAutoLayout__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setReverse__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setReverse (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setReverse__funptr __funptr__;
__funptr__ = (prim_Word_setReverse__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setAutoFormat__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setAutoFormat (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setAutoFormat__funptr __funptr__;
__funptr__ = (prim_Word_setAutoFormat__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_convert3__funptr) (void* arg1, MsoDiagramType arg2);
long prim_Word_convert3 (void* arg0, void* arg1, MsoDiagramType* arg2)
{
long res;
prim_Word_convert3__funptr __funptr__;
__funptr__ = (prim_Word_convert3__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_addCallout0__funptr) (void* arg1, MsoCalloutType arg2, float arg3, float arg4, float arg5, float arg6, void* arg7);
long prim_Word_addCallout0 (void* arg0, void* arg1, MsoCalloutType* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7)
{
long res;
prim_Word_addCallout0__funptr __funptr__;
__funptr__ = (prim_Word_addCallout0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7);
return (res);
}
typedef long (__stdcall * prim_Word_addConnector0__funptr) (void* arg1, MsoConnectorType arg2, float arg3, float arg4, float arg5, float arg6, void* arg7);
long prim_Word_addConnector0 (void* arg0, void* arg1, MsoConnectorType* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7)
{
long res;
prim_Word_addConnector0__funptr __funptr__;
__funptr__ = (prim_Word_addConnector0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7);
return (res);
}
typedef long (__stdcall * prim_Word_addLabel0__funptr) (void* arg1, MsoTextOrientation arg2, float arg3, float arg4, float arg5, float arg6, void* arg7);
long prim_Word_addLabel0 (void* arg0, void* arg1, MsoTextOrientation* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7)
{
long res;
prim_Word_addLabel0__funptr __funptr__;
__funptr__ = (prim_Word_addLabel0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7);
return (res);
}
typedef long (__stdcall * prim_Word_addTextEffect0__funptr) (void* arg1, MsoPresetTextEffect arg2, void* arg3, void* arg4, float arg5, MsoTriState arg6, MsoTriState arg7, float arg8, float arg9, void* arg10);
long prim_Word_addTextEffect0 (void* arg0, void* arg1, MsoPresetTextEffect* arg2, void* arg3, void* arg4, float arg5, MsoTriState* arg6, MsoTriState* arg7, float arg8, float arg9, void* arg10)
{
long res;
prim_Word_addTextEffect0__funptr __funptr__;
__funptr__ = (prim_Word_addTextEffect0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, *arg6, *arg7, arg8, arg9, arg10);
return (res);
}
typedef long (__stdcall * prim_Word_addTextbox0__funptr) (void* arg1, MsoTextOrientation arg2, float arg3, float arg4, float arg5, float arg6, void* arg7);
long prim_Word_addTextbox0 (void* arg0, void* arg1, MsoTextOrientation* arg2, float arg3, float arg4, float arg5, float arg6, void* arg7)
{
long res;
prim_Word_addTextbox0__funptr __funptr__;
__funptr__ = (prim_Word_addTextbox0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5, arg6, arg7);
return (res);
}
typedef long (__stdcall * prim_Word_buildFreeform0__funptr) (void* arg1, MsoEditingType arg2, float arg3, float arg4, void* arg5);
long prim_Word_buildFreeform0 (void* arg0, void* arg1, MsoEditingType* arg2, float arg3, float arg4, void* arg5)
{
long res;
prim_Word_buildFreeform0__funptr __funptr__;
__funptr__ = (prim_Word_buildFreeform0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4, arg5);
return (res);
}
typedef long (__stdcall * prim_Word_setType9__funptr) (void* arg1, MsoSoftEdgeType arg2);
long prim_Word_setType9 (void* arg0, void* arg1, MsoSoftEdgeType* arg2)
{
long res;
prim_Word_setType9__funptr __funptr__;
__funptr__ = (prim_Word_setType9__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setType10__funptr) (void* arg1, MsoReflectionType arg2);
long prim_Word_setType10 (void* arg0, void* arg1, MsoReflectionType* arg2)
{
long res;
prim_Word_setType10__funptr __funptr__;
__funptr__ = (prim_Word_setType10__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setChartType__funptr) (void* arg1, XlChartType arg2);
long prim_Word_setChartType (void* arg0, void* arg1, XlChartType* arg2)
{
long res;
prim_Word_setChartType__funptr __funptr__;
__funptr__ = (prim_Word_setChartType__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_applyCustomType__funptr) (void* arg1, XlChartType arg2, VARIANT arg3);
long prim_Word_applyCustomType (void* arg0, void* arg1, XlChartType* arg2, VARIANT* arg3)
{
long res;
prim_Word_applyCustomType__funptr __funptr__;
__funptr__ = (prim_Word_applyCustomType__funptr)arg0;
res =__funptr__(arg1, *arg2, *arg3);
return (res);
}
typedef long (__stdcall * prim_Word_setElement__funptr) (void* arg1, MsoChartElementType arg2);
long prim_Word_setElement (void* arg0, void* arg1, MsoChartElementType* arg2)
{
long res;
prim_Word_setElement__funptr __funptr__;
__funptr__ = (prim_Word_setElement__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_oneColorGradient0__funptr) (void* arg1, MsoGradientStyle arg2, long arg3, float arg4);
long prim_Word_oneColorGradient0 (void* arg0, void* arg1, MsoGradientStyle* arg2, long arg3, float arg4)
{
long res;
prim_Word_oneColorGradient0__funptr __funptr__;
__funptr__ = (prim_Word_oneColorGradient0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, arg4);
return (res);
}
typedef long (__stdcall * prim_Word_twoColorGradient0__funptr) (void* arg1, MsoGradientStyle arg2, long arg3);
long prim_Word_twoColorGradient0 (void* arg0, void* arg1, MsoGradientStyle* arg2, long arg3)
{
long res;
prim_Word_twoColorGradient0__funptr __funptr__;
__funptr__ = (prim_Word_twoColorGradient0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3);
return (res);
}
typedef long (__stdcall * prim_Word_presetTextured0__funptr) (void* arg1, MsoPresetTexture arg2);
long prim_Word_presetTextured0 (void* arg0, void* arg1, MsoPresetTexture* arg2)
{
long res;
prim_Word_presetTextured0__funptr __funptr__;
__funptr__ = (prim_Word_presetTextured0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_patterned0__funptr) (void* arg1, MsoPatternType arg2);
long prim_Word_patterned0 (void* arg0, void* arg1, MsoPatternType* arg2)
{
long res;
prim_Word_patterned0__funptr __funptr__;
__funptr__ = (prim_Word_patterned0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_presetGradient0__funptr) (void* arg1, MsoGradientStyle arg2, long arg3, MsoPresetGradientType arg4);
long prim_Word_presetGradient0 (void* arg0, void* arg1, MsoGradientStyle* arg2, long arg3, MsoPresetGradientType* arg4)
{
long res;
prim_Word_presetGradient0__funptr __funptr__;
__funptr__ = (prim_Word_presetGradient0__funptr)arg0;
res =__funptr__(arg1, *arg2, arg3, *arg4);
return (res);
}
typedef long (__stdcall * prim_Word_setVisible11__funptr) (void* arg1, MsoTriState arg2);
long prim_Word_setVisible11 (void* arg0, void* arg1, MsoTriState* arg2)
{
long res;
prim_Word_setVisible11__funptr __funptr__;
__funptr__ = (prim_Word_setVisible11__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_setChartType0__funptr) (void* arg1, XlChartType arg2);
long prim_Word_setChartType0 (void* arg0, void* arg1, XlChartType* arg2)
{
long res;
prim_Word_setChartType0__funptr __funptr__;
__funptr__ = (prim_Word_setChartType0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
typedef long (__stdcall * prim_Word_applyCustomType0__funptr) (void* arg1, XlChartType arg2);
long prim_Word_applyCustomType0 (void* arg0, void* arg1, XlChartType* arg2)
{
long res;
prim_Word_applyCustomType0__funptr __funptr__;
__funptr__ = (prim_Word_applyCustomType0__funptr)arg0;
res =__funptr__(arg1, *arg2);
return (res);
}
